<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zoom_pop_up_close_button</name>
   <tag></tag>
   <elementGuidId>88a1f11d-4f95-4b01-8f91-d96b382e7bb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.modal-close-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-close-btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;xs-up:bgc=body xs-up.fa-times:icon-before=cross state-loading modal-open&quot;]/ngb-modal-window[@class=&quot;d-block fade gallery-zoom-alpha leo-product-images-component leo-product-images-component-gallery-zoom-alpha md-up.thumbs-wrapper:d=none md-up.thumbs-wrapper:left=(50%) md-up.thumbs-wrapper:translate-x=n50 md-up.thumbs-wrapper:w=auto md-up.zoom-wrapper:pb=0 md-up&lt;&lt;.modal-open>>.modal-content:hmax=(90vh) md-up&lt;&lt;.modal-open>>.modal-content:m=(auto) md-up&lt;&lt;.modal-open>>.modal-content:wcalc=(100%|-|80px) modal modal-xxl show xs-up.image-gallery-container:flx-row-align=center-left xs-up.image-gallery-container:square=(100%) xs-up.modal-body:leri=0 xs-up.modal-body:p=0 xs-up.modal-body:pos=abs xs-up.modal-body:tobo=0 xs-up.modal-close-btn:before:fs=i4 xs-up.modal-close-btn:bgc=transparent xs-up.modal-close-btn:btn=white xs-up.modal-close-btn:bw=0 xs-up.modal-close-btn:icon-before=cross xs-up.modal-close-btn:ml=auto xs-up.modal-close-btn:p=2 xs-up.modal-close-btn:w=100 xs-up.modal-head:d=flx xs-up.modal-head:pos=abs xs-up.modal-head:right=0 xs-up.modal-head:top=0 xs-up.modal-head:w=(4rem) xs-up.modal-head:z=3 xs-up.thumbnail-media.active:bc=beta xs-up.thumbnail-media.active:bw-bottom=(0.25rem) xs-up.thumbnail-media:focus:oo=0 xs-up.thumbnail-media:focus:ow=0 xs-up.thumbnail-media:m=2 xs-up.thumbnail-media:pb=2 xs-up.thumbnail-media:w=(4.5rem) xs-up.thumbs-wrapper:bgc=body xs-up.thumbs-wrapper:bottom=3 xs-up.thumbs-wrapper:left=0 xs-up.thumbs-wrapper:pos=abs xs-up.thumbs-wrapper:scrollable=x xs-up.thumbs-wrapper:w=100 xs-up.thumbs-wrapper:z=3 xs-up.thumbs-wrapper>div:d=flx xs-up.thumbs-wrapper>div:flx-align-items=center xs-up.zoom-wrapper:pb=8 xs-up.zoom-wrapper:square=(100%) xs-up:d=block xs-up:d=flx xs-up:flx-dir=col xs-up:hmax=100 xs-up&lt;&lt;.modal-open>>.modal-dialog:h=100 xs-up&lt;&lt;.modal-open>>.modal-dialog:m=0 xs-up&lt;&lt;.modal-open>>.modal-dialog:w=100 xs-up&lt;&lt;.modal-open>>.modal-dialog:wmax=100 xs-up>>[leo-product-images-gallery]:h=100&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[1]/div[@class=&quot;image-gallery-container&quot;]/div[@class=&quot;modal-head&quot;]/button[@class=&quot;modal-close-btn&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngb-modal-window/div/div/div/div/div[2]/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
   </webElementXpaths>
</WebElementEntity>
