<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hompage_logo</name>
   <tag></tag>
   <elementGuidId>ed6edc6f-f728-4295-bdee-6bf6b5326404</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SimpleBannerLogo']/div/div/a/span/div/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/cb2-logo.svg?context=bWFzdGVyfGltYWdlc3wxNzMyfGltYWdlL3N2Zyt4bWx8aGQzL2g1ZS85NDI1NzIyODY3NzQyL2NiMi1sb2dvLnN2Z3xlNWIzMWZjYTU4ZGI5ZDgyZmE0MmI5ZjVhMTk1MDFkNzc4MzVkZWU2NjdlY2NiZjFjZjU3Mjc4NWYzNjkwMjU1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>CB2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SimpleBannerLogo&quot;)/div[@class=&quot;leo-simple-banner-component leo-simple-banner-component-logo-alpha xs-up:scrollable=none xs-up:w=(49px) xs-up:h=(28px) xs-up>>img:w=(49px) xs-up>>img:h=(27px) md-up:w=(110px) md-up:h=(61px) md-up>>img:w=(110px) md-up>>img:h=(61px) logo-alpha&quot;]/div[1]/a[@class=&quot;link state-active&quot;]/span[@class=&quot;img-wrapper is-initialized&quot;]/div[1]/picture[1]/img[@class=&quot;xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SimpleBannerLogo']/div/div/a/span/div/picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='CB2']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/cb2-logo.svg?context=bWFzdGVyfGltYWdlc3wxNzMyfGltYWdlL3N2Zyt4bWx8aGQzL2g1ZS85NDI1NzIyODY3NzQyL2NiMi1sb2dvLnN2Z3xlNWIzMWZjYTU4ZGI5ZDgyZmE0MmI5ZjVhMTk1MDFkNzc4MzVkZWU2NjdlY2NiZjFjZjU3Mjc4NWYzNjkwMjU1' and @alt = 'CB2']</value>
   </webElementXpaths>
</WebElementEntity>
