<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_id(RefinementFacetComponent)divclassleo_82906b</name>
   <tag></tag>
   <elementGuidId>c3c4476c-e982-4c27-a8a1-e26d7833968d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#katalon-rec_elementInfoDiv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='katalon-rec_elementInfoDiv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>katalon-rec_elementInfoDiv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>id(&quot;RefinementFacetComponent&quot;)/div[@class=&quot;leo-product-refinement-component leo-product-refinement-component-product-search-facet-selector-alpha xs-up.filters-title:ff=alpha xs-up.filters-title:txt-case=upper xs-up.filters-title:d=flx xs-up.filters-title:flx-justify-content=between xs-up.filters-title:py=(20px) xs-up.filters-title:px=4 xs-up.filters-title:fs=p4 xs-up.filters-title:bw-bottom=(1px) xs-up.filters-title:fw=medium xs-up.filters-title>>.total-count:ml=auto lg-up.filters-title:px=0 lg-up.filters-title:pr=4 lg-up.filters-title:mb=1 lg-up.filters-title:bw-bottom=0 lg-up.filters-title>>:lh=1.5 lg-up.filters-title>>>>.total-count:d=none xs-up.facet-item>>label:mt=0! xs-up.facet-item>>label:pt=0! xs-up.facet-item>>label:pl=6! xs-up.facet-item>>label:ff=beta xs-up.facet-item>>label:fs=(1.667rem) xs-up.facet-item>>label:txt-truncate=yes xs-up.facet-item>>label:before:top=(0.75rem)! xs-up.facet-item>>label:after:top=(0.75rem)! xs-up:ml=5 xs-up.btn-toggle-filters:mb=4 xs-up.facets:flx-row-align=top-left xs-up.facet:mb=1 xs-up.facet:py=4 xs-up.btn-facet-header:btn=body xs-up.btn-facet-header:btn-size=small xs-up.btn-facet-header:txt-case=upper xs-up.btn-facet-header:txt-truncate=yes xs-up.btn-facet-header:pos=rel xs-up.btn-facet-header:fw=medium xs-up.btn-facet-header:lh=1 xs-up.btn-facet-header:w=100 xs-up.btn-facet-header:after:ml=auto xs-up.btn-facet-header:not(.state-open):icon-after=chevron-down xs-up.btn-facet-header:not(.state-open):after:pos=rel xs-up.btn-facet-header:not(.state-open):after:top=(1px) xs-up.btn-facet-header:after:transition=transform xs-up.btn-facet-header:after:ml=1 xs-up.btn-facet-header.state-open:before:content=() xs-up.btn-facet-header.state-open:before:pos=abs xs-up.btn-facet-header.state-open:before:left=(5px) xs-up.btn-facet-header.state-open:before:right=(20px) xs-up.btn-facet-header.state-open:before:bottom=0 xs-up.btn-facet-header.state-open:before:bw-bottom=(1px) xs-up.btn-facet-header.state-open:before:bc=alpha xs-up.btn-facet-header.state-open:icon-after=chevron-up xs-up.facets-backdrop:d=none md-up.facets-backdrop:d=block xs-up.facets-backdrop:pos=abs xs-up.facets-backdrop:top=(4.35rem) xs-up.facets-backdrop:left=0 xs-up.facets-backdrop:w=100 xs-up.facets-backdrop:h=(100vh) xs-up.facets-backdrop:z=1 xs-up.facets-backdrop:bgc=body-50 xs-up.facet-body-wrapper:pos=abs xs-up.facet-body-wrapper:bgc=white xs-up.facet-body-wrapper:z=1 xs-up.facet-body-wrapper:leri=0 xs-up.facet-body-wrapper:px=7 xs-up.facet-body-wrapper:mx=n3 xs-up.facet-body-wrapper:pt=(1.67rem) xs-up.facet-body-wrapper:bw-bottom=(1px) xs-up.facet-body-wrapper:bs=(0|3px|5px|0|#1A000000) xs-up&lt;&lt;[sticky]>>.facet-body-wrapper:pos=fix xs-up&lt;&lt;[sticky]>>.facet-body-wrapper:top=(101px) xs-up&lt;&lt;[sticky]>>.facet-body-wrapper:mx=0 xs-up.facet-body:d=flx xs-up.facet-body:flx-wrap=yes! xs-up.facet-body:scrollable=y xs-up.facet-body:hmaxcalc=(100vh|-|15.25rem) xs-up&lt;&lt;[sticky]>>.facet-body:hmaxcalc=(100vh|-|15.25rem) xs-up.facet-item:w=25 xs-up.facet-item:fs=25 xs-up.body-controls:mt=(1.67rem) xs-up.body-controls:d=flx xs-up.body-controls:bw-top=(1px) xs-up.body-controls>>button:btn-outline=alpha xs-up.body-controls>>button:bw=0 xs-up.body-controls>>button:fs=p4 xs-up.body-controls>>button:fw=medium xs-up.body-controls>>button:w=50 xs-up.body-controls>>button:h=(3.25rem) xs-up.btn-clear-all:bw-right=(1px)! xs-up:product-search-facet-selector-beta lg-up:product-search-facet-selector-alpha&quot;]/div[1]/div[@class=&quot;facets&quot;]/div[@class=&quot;facet&quot;]/button[@class=&quot;btn-facet-header state-close&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon-rec_elementInfoDiv&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='katalon-rec_elementInfoDiv']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='katalon']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COPYRIGHT © 2021 ALLSAINTS ALL RIGHTS RESERVED*ORDERS BEFORE 7PM'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEND'])[1]/following::div[24]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/preceding::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='id(&quot;RefinementFacetComponent&quot;)/div[@class=&quot;leo-product-refinement-component leo-product-refinement-component-product-search-facet-selector-alpha xs-up.filters-title:ff=alpha xs-up.filters-title:txt-case=upper xs-up.filters-title:d=flx xs-up.filters-title:flx-justify-content=between xs-up.filters-title:py=(20px) xs-up.filters-title:px=4 xs-up.filters-title:fs=p4 xs-up.filters-title:bw-bottom=(1px) xs-up.filters-title:fw=medium xs-up.filters-title>>.total-count:ml=auto lg-up.filters-title:px=0 lg-up.filters-title:pr=4 lg-up.filters-title:mb=1 lg-up.filters-title:bw-bottom=0 lg-up.filters-title>>:lh=1.5 lg-up.filters-title>>>>.total-count:d=none xs-up.facet-item>>label:mt=0! xs-up.facet-item>>label:pt=0! xs-up.facet-item>>label:pl=6! xs-up.facet-item>>label:ff=beta xs-up.facet-item>>label:fs=(1.667rem) xs-up.facet-item>>label:txt-truncate=yes xs-up.facet-item>>label:before:top=(0.75rem)! xs-up.facet-item>>label:after:top=(0.75rem)! xs-up:ml=5 xs-up.btn-toggle-filters:mb=4 xs-up.facets:flx-row-align=top-left xs-up.facet:mb=1 xs-up.facet:py=4 xs-up.btn-facet-header:btn=body xs-up.btn-facet-header:btn-size=small xs-up.btn-facet-header:txt-case=upper xs-up.btn-facet-header:txt-truncate=yes xs-up.btn-facet-header:pos=rel xs-up.btn-facet-header:fw=medium xs-up.btn-facet-header:lh=1 xs-up.btn-facet-header:w=100 xs-up.btn-facet-header:after:ml=auto xs-up.btn-facet-header:not(.state-open):icon-after=chevron-down xs-up.btn-facet-header:not(.state-open):after:pos=rel xs-up.btn-facet-header:not(.state-open):after:top=(1px) xs-up.btn-facet-header:after:transition=transform xs-up.btn-facet-header:after:ml=1 xs-up.btn-facet-header.state-open:before:content=() xs-up.btn-facet-header.state-open:before:pos=abs xs-up.btn-facet-header.state-open:before:left=(5px) xs-up.btn-facet-header.state-open:before:right=(20px) xs-up.btn-facet-header.state-open:before:bottom=0 xs-up.btn-facet-header.state-open:before:bw-bottom=(1px) xs-up.btn-facet-header.state-open:before:bc=alpha xs-up.btn-facet-header.state-open:icon-after=chevron-up xs-up.facets-backdrop:d=none md-up.facets-backdrop:d=block xs-up.facets-backdrop:pos=abs xs-up.facets-backdrop:top=(4.35rem) xs-up.facets-backdrop:left=0 xs-up.facets-backdrop:w=100 xs-up.facets-backdrop:h=(100vh) xs-up.facets-backdrop:z=1 xs-up.facets-backdrop:bgc=body-50 xs-up.facet-body-wrapper:pos=abs xs-up.facet-body-wrapper:bgc=white xs-up.facet-body-wrapper:z=1 xs-up.facet-body-wrapper:leri=0 xs-up.facet-body-wrapper:px=7 xs-up.facet-body-wrapper:mx=n3 xs-up.facet-body-wrapper:pt=(1.67rem) xs-up.facet-body-wrapper:bw-bottom=(1px) xs-up.facet-body-wrapper:bs=(0|3px|5px|0|#1A000000) xs-up&lt;&lt;[sticky]>>.facet-body-wrapper:pos=fix xs-up&lt;&lt;[sticky]>>.facet-body-wrapper:top=(101px) xs-up&lt;&lt;[sticky]>>.facet-body-wrapper:mx=0 xs-up.facet-body:d=flx xs-up.facet-body:flx-wrap=yes! xs-up.facet-body:scrollable=y xs-up.facet-body:hmaxcalc=(100vh|-|15.25rem) xs-up&lt;&lt;[sticky]>>.facet-body:hmaxcalc=(100vh|-|15.25rem) xs-up.facet-item:w=25 xs-up.facet-item:fs=25 xs-up.body-controls:mt=(1.67rem) xs-up.body-controls:d=flx xs-up.body-controls:bw-top=(1px) xs-up.body-controls>>button:btn-outline=alpha xs-up.body-controls>>button:bw=0 xs-up.body-controls>>button:fs=p4 xs-up.body-controls>>button:fw=medium xs-up.body-controls>>button:w=50 xs-up.body-controls>>button:h=(3.25rem) xs-up.btn-clear-all:bw-right=(1px)! xs-up:product-search-facet-selector-beta lg-up:product-search-facet-selector-alpha&quot;]/div[1]/div[@class=&quot;facets&quot;]/div[@class=&quot;facet&quot;]/button[@class=&quot;btn-facet-header state-close&quot;]']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'katalon-rec_elementInfoDiv' and (text() = 'id(&quot;RefinementFacetComponent&quot;)/div[@class=&quot;leo-product-refinement-component leo-product-refinement-component-product-search-facet-selector-alpha xs-up.filters-title:ff=alpha xs-up.filters-title:txt-case=upper xs-up.filters-title:d=flx xs-up.filters-title:flx-justify-content=between xs-up.filters-title:py=(20px) xs-up.filters-title:px=4 xs-up.filters-title:fs=p4 xs-up.filters-title:bw-bottom=(1px) xs-up.filters-title:fw=medium xs-up.filters-title>>.total-count:ml=auto lg-up.filters-title:px=0 lg-up.filters-title:pr=4 lg-up.filters-title:mb=1 lg-up.filters-title:bw-bottom=0 lg-up.filters-title>>:lh=1.5 lg-up.filters-title>>>>.total-count:d=none xs-up.facet-item>>label:mt=0! xs-up.facet-item>>label:pt=0! xs-up.facet-item>>label:pl=6! xs-up.facet-item>>label:ff=beta xs-up.facet-item>>label:fs=(1.667rem) xs-up.facet-item>>label:txt-truncate=yes xs-up.facet-item>>label:before:top=(0.75rem)! xs-up.facet-item>>label:after:top=(0.75rem)! xs-up:ml=5 xs-up.btn-toggle-filters:mb=4 xs-up.facets:flx-row-align=top-left xs-up.facet:mb=1 xs-up.facet:py=4 xs-up.btn-facet-header:btn=body xs-up.btn-facet-header:btn-size=small xs-up.btn-facet-header:txt-case=upper xs-up.btn-facet-header:txt-truncate=yes xs-up.btn-facet-header:pos=rel xs-up.btn-facet-header:fw=medium xs-up.btn-facet-header:lh=1 xs-up.btn-facet-header:w=100 xs-up.btn-facet-header:after:ml=auto xs-up.btn-facet-header:not(.state-open):icon-after=chevron-down xs-up.btn-facet-header:not(.state-open):after:pos=rel xs-up.btn-facet-header:not(.state-open):after:top=(1px) xs-up.btn-facet-header:after:transition=transform xs-up.btn-facet-header:after:ml=1 xs-up.btn-facet-header.state-open:before:content=() xs-up.btn-facet-header.state-open:before:pos=abs xs-up.btn-facet-header.state-open:before:left=(5px) xs-up.btn-facet-header.state-open:before:right=(20px) xs-up.btn-facet-header.state-open:before:bottom=0 xs-up.btn-facet-header.state-open:before:bw-bottom=(1px) xs-up.btn-facet-header.state-open:before:bc=alpha xs-up.btn-facet-header.state-open:icon-after=chevron-up xs-up.facets-backdrop:d=none md-up.facets-backdrop:d=block xs-up.facets-backdrop:pos=abs xs-up.facets-backdrop:top=(4.35rem) xs-up.facets-backdrop:left=0 xs-up.facets-backdrop:w=100 xs-up.facets-backdrop:h=(100vh) xs-up.facets-backdrop:z=1 xs-up.facets-backdrop:bgc=body-50 xs-up.facet-body-wrapper:pos=abs xs-up.facet-body-wrapper:bgc=white xs-up.facet-body-wrapper:z=1 xs-up.facet-body-wrapper:leri=0 xs-up.facet-body-wrapper:px=7 xs-up.facet-body-wrapper:mx=n3 xs-up.facet-body-wrapper:pt=(1.67rem) xs-up.facet-body-wrapper:bw-bottom=(1px) xs-up.facet-body-wrapper:bs=(0|3px|5px|0|#1A000000) xs-up&lt;&lt;[sticky]>>.facet-body-wrapper:pos=fix xs-up&lt;&lt;[sticky]>>.facet-body-wrapper:top=(101px) xs-up&lt;&lt;[sticky]>>.facet-body-wrapper:mx=0 xs-up.facet-body:d=flx xs-up.facet-body:flx-wrap=yes! xs-up.facet-body:scrollable=y xs-up.facet-body:hmaxcalc=(100vh|-|15.25rem) xs-up&lt;&lt;[sticky]>>.facet-body:hmaxcalc=(100vh|-|15.25rem) xs-up.facet-item:w=25 xs-up.facet-item:fs=25 xs-up.body-controls:mt=(1.67rem) xs-up.body-controls:d=flx xs-up.body-controls:bw-top=(1px) xs-up.body-controls>>button:btn-outline=alpha xs-up.body-controls>>button:bw=0 xs-up.body-controls>>button:fs=p4 xs-up.body-controls>>button:fw=medium xs-up.body-controls>>button:w=50 xs-up.body-controls>>button:h=(3.25rem) xs-up.btn-clear-all:bw-right=(1px)! xs-up:product-search-facet-selector-beta lg-up:product-search-facet-selector-alpha&quot;]/div[1]/div[@class=&quot;facets&quot;]/div[@class=&quot;facet&quot;]/button[@class=&quot;btn-facet-header state-close&quot;]' or . = 'id(&quot;RefinementFacetComponent&quot;)/div[@class=&quot;leo-product-refinement-component leo-product-refinement-component-product-search-facet-selector-alpha xs-up.filters-title:ff=alpha xs-up.filters-title:txt-case=upper xs-up.filters-title:d=flx xs-up.filters-title:flx-justify-content=between xs-up.filters-title:py=(20px) xs-up.filters-title:px=4 xs-up.filters-title:fs=p4 xs-up.filters-title:bw-bottom=(1px) xs-up.filters-title:fw=medium xs-up.filters-title>>.total-count:ml=auto lg-up.filters-title:px=0 lg-up.filters-title:pr=4 lg-up.filters-title:mb=1 lg-up.filters-title:bw-bottom=0 lg-up.filters-title>>:lh=1.5 lg-up.filters-title>>>>.total-count:d=none xs-up.facet-item>>label:mt=0! xs-up.facet-item>>label:pt=0! xs-up.facet-item>>label:pl=6! xs-up.facet-item>>label:ff=beta xs-up.facet-item>>label:fs=(1.667rem) xs-up.facet-item>>label:txt-truncate=yes xs-up.facet-item>>label:before:top=(0.75rem)! xs-up.facet-item>>label:after:top=(0.75rem)! xs-up:ml=5 xs-up.btn-toggle-filters:mb=4 xs-up.facets:flx-row-align=top-left xs-up.facet:mb=1 xs-up.facet:py=4 xs-up.btn-facet-header:btn=body xs-up.btn-facet-header:btn-size=small xs-up.btn-facet-header:txt-case=upper xs-up.btn-facet-header:txt-truncate=yes xs-up.btn-facet-header:pos=rel xs-up.btn-facet-header:fw=medium xs-up.btn-facet-header:lh=1 xs-up.btn-facet-header:w=100 xs-up.btn-facet-header:after:ml=auto xs-up.btn-facet-header:not(.state-open):icon-after=chevron-down xs-up.btn-facet-header:not(.state-open):after:pos=rel xs-up.btn-facet-header:not(.state-open):after:top=(1px) xs-up.btn-facet-header:after:transition=transform xs-up.btn-facet-header:after:ml=1 xs-up.btn-facet-header.state-open:before:content=() xs-up.btn-facet-header.state-open:before:pos=abs xs-up.btn-facet-header.state-open:before:left=(5px) xs-up.btn-facet-header.state-open:before:right=(20px) xs-up.btn-facet-header.state-open:before:bottom=0 xs-up.btn-facet-header.state-open:before:bw-bottom=(1px) xs-up.btn-facet-header.state-open:before:bc=alpha xs-up.btn-facet-header.state-open:icon-after=chevron-up xs-up.facets-backdrop:d=none md-up.facets-backdrop:d=block xs-up.facets-backdrop:pos=abs xs-up.facets-backdrop:top=(4.35rem) xs-up.facets-backdrop:left=0 xs-up.facets-backdrop:w=100 xs-up.facets-backdrop:h=(100vh) xs-up.facets-backdrop:z=1 xs-up.facets-backdrop:bgc=body-50 xs-up.facet-body-wrapper:pos=abs xs-up.facet-body-wrapper:bgc=white xs-up.facet-body-wrapper:z=1 xs-up.facet-body-wrapper:leri=0 xs-up.facet-body-wrapper:px=7 xs-up.facet-body-wrapper:mx=n3 xs-up.facet-body-wrapper:pt=(1.67rem) xs-up.facet-body-wrapper:bw-bottom=(1px) xs-up.facet-body-wrapper:bs=(0|3px|5px|0|#1A000000) xs-up&lt;&lt;[sticky]>>.facet-body-wrapper:pos=fix xs-up&lt;&lt;[sticky]>>.facet-body-wrapper:top=(101px) xs-up&lt;&lt;[sticky]>>.facet-body-wrapper:mx=0 xs-up.facet-body:d=flx xs-up.facet-body:flx-wrap=yes! xs-up.facet-body:scrollable=y xs-up.facet-body:hmaxcalc=(100vh|-|15.25rem) xs-up&lt;&lt;[sticky]>>.facet-body:hmaxcalc=(100vh|-|15.25rem) xs-up.facet-item:w=25 xs-up.facet-item:fs=25 xs-up.body-controls:mt=(1.67rem) xs-up.body-controls:d=flx xs-up.body-controls:bw-top=(1px) xs-up.body-controls>>button:btn-outline=alpha xs-up.body-controls>>button:bw=0 xs-up.body-controls>>button:fs=p4 xs-up.body-controls>>button:fw=medium xs-up.body-controls>>button:w=50 xs-up.body-controls>>button:h=(3.25rem) xs-up.btn-clear-all:bw-right=(1px)! xs-up:product-search-facet-selector-beta lg-up:product-search-facet-selector-alpha&quot;]/div[1]/div[@class=&quot;facets&quot;]/div[@class=&quot;facet&quot;]/button[@class=&quot;btn-facet-header state-close&quot;]')]</value>
   </webElementXpaths>
</WebElementEntity>
