<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_id(ProductListComponent)divclassleo-pro_9dd190</name>
   <tag></tag>
   <elementGuidId>f6b2ae0c-a552-4606-9b6c-f96a7e5c3a04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='katalon-rec_elementInfoDiv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#katalon-rec_elementInfoDiv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>katalon-rec_elementInfoDiv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>id(&quot;ProductListComponent&quot;)/div[@class=&quot;leo-product-list-component leo-product-list-component-product-grid-alpha-three-columns xs-up:product-grid:pos=rel xs-up:product-grid-col-item-inner:h=100 xs-up:ff=beta xs-up:hmin=(400px) md-up:hmin=(500px) lg-up:hmin=(700px) xs-up:product-grid-container:px=4 lg-up:product-grid-container:px=(5.5rem) lg-up:product-grid-container:wmax=100 xs-up:product-grid-row-group:mb=5 xs-up:product-grid-col-item-inner:d=flx xs-up:product-grid-col-item-inner:flx-dir=col xs-up:product-grid-col-item-inner:pos=rel xs-up:product-grid-col-item-inner:pr=0 md-up:product-grid-col-item-inner:pr=6 xs-up:product-grid-col-item-inner:pl=0 md-up:product-grid-col-item-inner:pl=0 lg-up:product-grid-col-item-inner:pl=0 xs-up.row-image+.row:mt=5 xs-up.row-image>.col-item>.col-item-inner:px=0! md-up.row-add-to-wishlist>>.col-item:hover>>.tile-add-to-wishlist:d=flx lg-up.tile-add-to-wishlist:d=none xs-up.tile-add-to-wishlist:pos-align=top-right xs-up.tile-add-to-wishlist>>.btn-wishlist:before:square=(1.333rem) xs-up.tile-add-to-wishlist:bottom=auto md-down>>.col-6>>.tile-add-to-wishlist:bottom=2 md-down>>.col-6>>.tile-add-to-wishlist:top=auto lg-up.tile-add-to-wishlist:top=n1 xs-up.tile-variant-selector-advanced>>.features-group:mb=3 xs-up.tile-variant-selected-item>>.variant-list:mb=3 xs-up.tile-name:pr=7 md-down>>.col-6>>.tile-name:pr=0 xs-up.tile-summary>>.summary:mb=3 xs-up.tile-add-to-cart:mt=auto xs-up.tile-image:d=flx xs-up.tile-image:h=100 xs-up.tile-image>div:w=100 xs-up:product-grid-alpha-two-columns lg-up:product-grid-alpha-three-columns md-down.tile-variant-selector-simple>>.size:d=none&quot;]/div[1]/div[@class=&quot;container container-grid&quot;]/div[@class=&quot;row-group&quot;]/div[@class=&quot;row row-add-to-wishlist row-badges row-name row-price row-variant-selector-simple row-add-to-cart row-stock-badge-cta&quot;]/div[@class=&quot;col-item col-4&quot;]/div[@class=&quot;col-item-inner&quot;]/div[@class=&quot;tile tile-variant-selector-simple&quot;]/div[@id=&quot;undefined&quot;]/div[@class=&quot;leo-product-variant-selector-component leo-product-variant-selector-component-product-variant-selector-simple-alpha xs-up.variant-list:flx-row-align=center-left xs-up.dropdown-toggle:after:d=none xs-up:ff=alpha xs-up:mb=3 xs-up.variant-list:pos=rel xs-up.variant-list:pt=3 xs-up.variant-group-title:d=none xs-up.variant-list:flx-wrap=yes xs-up.variant-list-item:mr=2 xs-up.variant-list-item:mb=auto xs-up.btn-more:btn=body xs-up.btn-more:btn-size=small xs-up.btn-more:fw=medium xs-up.btn-more:p=0 xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:d=flx xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:py=2 xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:fs=p3 xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:fw=semi xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:fc=warning xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:mb=3 xs-up.tooltip>>p:m=0 xs-up:product-variant-selector-simple-gamma md-up:product-variant-selector-simple-alpha&quot;]/div[1]/div[@class=&quot;variant-group&quot;]/div[@class=&quot;variant-list size&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon-rec_elementInfoDiv&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='katalon-rec_elementInfoDiv']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='katalon']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COPYRIGHT © 2021 ALLSAINTS ALL RIGHTS RESERVED*ORDERS BEFORE 7PM'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEND'])[1]/following::div[24]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/preceding::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='id(&quot;ProductListComponent&quot;)/div[@class=&quot;leo-product-list-component leo-product-list-component-product-grid-alpha-three-columns xs-up:product-grid:pos=rel xs-up:product-grid-col-item-inner:h=100 xs-up:ff=beta xs-up:hmin=(400px) md-up:hmin=(500px) lg-up:hmin=(700px) xs-up:product-grid-container:px=4 lg-up:product-grid-container:px=(5.5rem) lg-up:product-grid-container:wmax=100 xs-up:product-grid-row-group:mb=5 xs-up:product-grid-col-item-inner:d=flx xs-up:product-grid-col-item-inner:flx-dir=col xs-up:product-grid-col-item-inner:pos=rel xs-up:product-grid-col-item-inner:pr=0 md-up:product-grid-col-item-inner:pr=6 xs-up:product-grid-col-item-inner:pl=0 md-up:product-grid-col-item-inner:pl=0 lg-up:product-grid-col-item-inner:pl=0 xs-up.row-image+.row:mt=5 xs-up.row-image>.col-item>.col-item-inner:px=0! md-up.row-add-to-wishlist>>.col-item:hover>>.tile-add-to-wishlist:d=flx lg-up.tile-add-to-wishlist:d=none xs-up.tile-add-to-wishlist:pos-align=top-right xs-up.tile-add-to-wishlist>>.btn-wishlist:before:square=(1.333rem) xs-up.tile-add-to-wishlist:bottom=auto md-down>>.col-6>>.tile-add-to-wishlist:bottom=2 md-down>>.col-6>>.tile-add-to-wishlist:top=auto lg-up.tile-add-to-wishlist:top=n1 xs-up.tile-variant-selector-advanced>>.features-group:mb=3 xs-up.tile-variant-selected-item>>.variant-list:mb=3 xs-up.tile-name:pr=7 md-down>>.col-6>>.tile-name:pr=0 xs-up.tile-summary>>.summary:mb=3 xs-up.tile-add-to-cart:mt=auto xs-up.tile-image:d=flx xs-up.tile-image:h=100 xs-up.tile-image>div:w=100 xs-up:product-grid-alpha-two-columns lg-up:product-grid-alpha-three-columns md-down.tile-variant-selector-simple>>.size:d=none&quot;]/div[1]/div[@class=&quot;container container-grid&quot;]/div[@class=&quot;row-group&quot;]/div[@class=&quot;row row-add-to-wishlist row-badges row-name row-price row-variant-selector-simple row-add-to-cart row-stock-badge-cta&quot;]/div[@class=&quot;col-item col-4&quot;]/div[@class=&quot;col-item-inner&quot;]/div[@class=&quot;tile tile-variant-selector-simple&quot;]/div[@id=&quot;undefined&quot;]/div[@class=&quot;leo-product-variant-selector-component leo-product-variant-selector-component-product-variant-selector-simple-alpha xs-up.variant-list:flx-row-align=center-left xs-up.dropdown-toggle:after:d=none xs-up:ff=alpha xs-up:mb=3 xs-up.variant-list:pos=rel xs-up.variant-list:pt=3 xs-up.variant-group-title:d=none xs-up.variant-list:flx-wrap=yes xs-up.variant-list-item:mr=2 xs-up.variant-list-item:mb=auto xs-up.btn-more:btn=body xs-up.btn-more:btn-size=small xs-up.btn-more:fw=medium xs-up.btn-more:p=0 xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:d=flx xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:py=2 xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:fs=p3 xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:fw=semi xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:fc=warning xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:mb=3 xs-up.tooltip>>p:m=0 xs-up:product-variant-selector-simple-gamma md-up:product-variant-selector-simple-alpha&quot;]/div[1]/div[@class=&quot;variant-group&quot;]/div[@class=&quot;variant-list size&quot;]']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'katalon-rec_elementInfoDiv' and (text() = 'id(&quot;ProductListComponent&quot;)/div[@class=&quot;leo-product-list-component leo-product-list-component-product-grid-alpha-three-columns xs-up:product-grid:pos=rel xs-up:product-grid-col-item-inner:h=100 xs-up:ff=beta xs-up:hmin=(400px) md-up:hmin=(500px) lg-up:hmin=(700px) xs-up:product-grid-container:px=4 lg-up:product-grid-container:px=(5.5rem) lg-up:product-grid-container:wmax=100 xs-up:product-grid-row-group:mb=5 xs-up:product-grid-col-item-inner:d=flx xs-up:product-grid-col-item-inner:flx-dir=col xs-up:product-grid-col-item-inner:pos=rel xs-up:product-grid-col-item-inner:pr=0 md-up:product-grid-col-item-inner:pr=6 xs-up:product-grid-col-item-inner:pl=0 md-up:product-grid-col-item-inner:pl=0 lg-up:product-grid-col-item-inner:pl=0 xs-up.row-image+.row:mt=5 xs-up.row-image>.col-item>.col-item-inner:px=0! md-up.row-add-to-wishlist>>.col-item:hover>>.tile-add-to-wishlist:d=flx lg-up.tile-add-to-wishlist:d=none xs-up.tile-add-to-wishlist:pos-align=top-right xs-up.tile-add-to-wishlist>>.btn-wishlist:before:square=(1.333rem) xs-up.tile-add-to-wishlist:bottom=auto md-down>>.col-6>>.tile-add-to-wishlist:bottom=2 md-down>>.col-6>>.tile-add-to-wishlist:top=auto lg-up.tile-add-to-wishlist:top=n1 xs-up.tile-variant-selector-advanced>>.features-group:mb=3 xs-up.tile-variant-selected-item>>.variant-list:mb=3 xs-up.tile-name:pr=7 md-down>>.col-6>>.tile-name:pr=0 xs-up.tile-summary>>.summary:mb=3 xs-up.tile-add-to-cart:mt=auto xs-up.tile-image:d=flx xs-up.tile-image:h=100 xs-up.tile-image>div:w=100 xs-up:product-grid-alpha-two-columns lg-up:product-grid-alpha-three-columns md-down.tile-variant-selector-simple>>.size:d=none&quot;]/div[1]/div[@class=&quot;container container-grid&quot;]/div[@class=&quot;row-group&quot;]/div[@class=&quot;row row-add-to-wishlist row-badges row-name row-price row-variant-selector-simple row-add-to-cart row-stock-badge-cta&quot;]/div[@class=&quot;col-item col-4&quot;]/div[@class=&quot;col-item-inner&quot;]/div[@class=&quot;tile tile-variant-selector-simple&quot;]/div[@id=&quot;undefined&quot;]/div[@class=&quot;leo-product-variant-selector-component leo-product-variant-selector-component-product-variant-selector-simple-alpha xs-up.variant-list:flx-row-align=center-left xs-up.dropdown-toggle:after:d=none xs-up:ff=alpha xs-up:mb=3 xs-up.variant-list:pos=rel xs-up.variant-list:pt=3 xs-up.variant-group-title:d=none xs-up.variant-list:flx-wrap=yes xs-up.variant-list-item:mr=2 xs-up.variant-list-item:mb=auto xs-up.btn-more:btn=body xs-up.btn-more:btn-size=small xs-up.btn-more:fw=medium xs-up.btn-more:p=0 xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:d=flx xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:py=2 xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:fs=p3 xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:fw=semi xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:fc=warning xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:mb=3 xs-up.tooltip>>p:m=0 xs-up:product-variant-selector-simple-gamma md-up:product-variant-selector-simple-alpha&quot;]/div[1]/div[@class=&quot;variant-group&quot;]/div[@class=&quot;variant-list size&quot;]' or . = 'id(&quot;ProductListComponent&quot;)/div[@class=&quot;leo-product-list-component leo-product-list-component-product-grid-alpha-three-columns xs-up:product-grid:pos=rel xs-up:product-grid-col-item-inner:h=100 xs-up:ff=beta xs-up:hmin=(400px) md-up:hmin=(500px) lg-up:hmin=(700px) xs-up:product-grid-container:px=4 lg-up:product-grid-container:px=(5.5rem) lg-up:product-grid-container:wmax=100 xs-up:product-grid-row-group:mb=5 xs-up:product-grid-col-item-inner:d=flx xs-up:product-grid-col-item-inner:flx-dir=col xs-up:product-grid-col-item-inner:pos=rel xs-up:product-grid-col-item-inner:pr=0 md-up:product-grid-col-item-inner:pr=6 xs-up:product-grid-col-item-inner:pl=0 md-up:product-grid-col-item-inner:pl=0 lg-up:product-grid-col-item-inner:pl=0 xs-up.row-image+.row:mt=5 xs-up.row-image>.col-item>.col-item-inner:px=0! md-up.row-add-to-wishlist>>.col-item:hover>>.tile-add-to-wishlist:d=flx lg-up.tile-add-to-wishlist:d=none xs-up.tile-add-to-wishlist:pos-align=top-right xs-up.tile-add-to-wishlist>>.btn-wishlist:before:square=(1.333rem) xs-up.tile-add-to-wishlist:bottom=auto md-down>>.col-6>>.tile-add-to-wishlist:bottom=2 md-down>>.col-6>>.tile-add-to-wishlist:top=auto lg-up.tile-add-to-wishlist:top=n1 xs-up.tile-variant-selector-advanced>>.features-group:mb=3 xs-up.tile-variant-selected-item>>.variant-list:mb=3 xs-up.tile-name:pr=7 md-down>>.col-6>>.tile-name:pr=0 xs-up.tile-summary>>.summary:mb=3 xs-up.tile-add-to-cart:mt=auto xs-up.tile-image:d=flx xs-up.tile-image:h=100 xs-up.tile-image>div:w=100 xs-up:product-grid-alpha-two-columns lg-up:product-grid-alpha-three-columns md-down.tile-variant-selector-simple>>.size:d=none&quot;]/div[1]/div[@class=&quot;container container-grid&quot;]/div[@class=&quot;row-group&quot;]/div[@class=&quot;row row-add-to-wishlist row-badges row-name row-price row-variant-selector-simple row-add-to-cart row-stock-badge-cta&quot;]/div[@class=&quot;col-item col-4&quot;]/div[@class=&quot;col-item-inner&quot;]/div[@class=&quot;tile tile-variant-selector-simple&quot;]/div[@id=&quot;undefined&quot;]/div[@class=&quot;leo-product-variant-selector-component leo-product-variant-selector-component-product-variant-selector-simple-alpha xs-up.variant-list:flx-row-align=center-left xs-up.dropdown-toggle:after:d=none xs-up:ff=alpha xs-up:mb=3 xs-up.variant-list:pos=rel xs-up.variant-list:pt=3 xs-up.variant-group-title:d=none xs-up.variant-list:flx-wrap=yes xs-up.variant-list-item:mr=2 xs-up.variant-list-item:mb=auto xs-up.btn-more:btn=body xs-up.btn-more:btn-size=small xs-up.btn-more:fw=medium xs-up.btn-more:p=0 xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:d=flx xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:py=2 xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:fs=p3 xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:fw=semi xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:fc=warning xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:mb=3 xs-up.tooltip>>p:m=0 xs-up:product-variant-selector-simple-gamma md-up:product-variant-selector-simple-alpha&quot;]/div[1]/div[@class=&quot;variant-group&quot;]/div[@class=&quot;variant-list size&quot;]')]</value>
   </webElementXpaths>
</WebElementEntity>
