<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_price</name>
   <tag></tag>
   <elementGuidId>61e472e4-20f1-40df-97ba-596e52e09a94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='undefined']/div/div/div)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AED 1,375.00</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductIntroComponent&quot;)/div[@class=&quot;leo-product-intro-component leo-product-intro-component-product-intro-alpha xs-up:mt=4 md-up:mt=0 xs-up:px=3 xs-up.intro-wrapper:d=flx xs-up.intro-wrapper:flx-dir=col xs-up.intro-wrapper:bgc=white! xs-up.intro-wrapper:z=1! xs-up.intro-wrapper:txt-case=upper xs-up[leo-product-intro]:d=flx xs-up[leo-product-intro]:flx-dir=col xs-up.product-sku:flx-order=2 xs-up.intro-wrapper>>.product-price:flx-order=1 xs-up.intro-wrapper>>.product-sku:flx-order=2 product-intro-alpha&quot;]/div[1]/div[@class=&quot;product-price&quot;]/div[@id=&quot;undefined&quot;]/div[@class=&quot;leo-product-price-component leo-product-price-component-product-price-gamma xs-up.price:fs=p3 sm-up.price:fs=p2 md-up.price:fs=p3 lg-up.price:fs=p2 xs-up.price:fw=semi xs-up.price.state-cross:fc=danger xs-up.crossed-price:fc=black-70 xs-up.crossed-price:txt-line-through=yes sm-down.price:mb=(0.75rem) md-up.price:mb=(0.75rem) xs-up[leo-product-price]:flx-row-align=bottom-left xs-up[leo-product-price]:lh=1 xs-up.price:mr=2 xs-up.crossed-price:fs=p4 product-price-gamma&quot;]/div[1]/div[@class=&quot;price&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='undefined']/div/div/div)[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKU: 461977_CB2'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chelsea Home Office Chair'])[2]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AED 1,375.00']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[4]/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AED 1,375.00' or . = 'AED 1,375.00')]</value>
   </webElementXpaths>
</WebElementEntity>
