<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close_qualtrics_popup</name>
   <tag></tag>
   <elementGuidId>dcc46857-128c-4cd8-963e-157ebee5fa08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='Close'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.QSIWebResponsiveDialog-Layout1-SI_3F5qDwQezidzQBN_close-btn > img[alt=&quot;Close&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://siteintercept.qualtrics.com/WRSiteInterceptEngine/../WRQualtricsShared/Graphics/siteintercept/wr-dialog-close-btn-black.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Close</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;xs-up:bgc=body xs-up.fa-times:icon-before=cross state-loading&quot;]/div[@class=&quot;QSIWebResponsive&quot;]/div[@class=&quot;QSIWebResponsive-creative-container-fade&quot;]/div[@class=&quot;QSIWebResponsiveDialog-Layout1-SI_3F5qDwQezidzQBN_content QSIWebResponsiveDialog-Layout1-SI_3F5qDwQezidzQBN_content-medium QSIWebResponsiveDialog-Layout1-SI_3F5qDwQezidzQBN_border-radius-none QSIWebResponsiveDialog-Layout1-SI_3F5qDwQezidzQBN_drop-shadow-medium&quot;]/div[@class=&quot;QSIWebResponsiveDialog-Layout1-SI_3F5qDwQezidzQBN_close-btn-container QSIWebResponsiveDialog-Layout1-SI_3F5qDwQezidzQBN_close-btn-container-medium&quot;]/button[@class=&quot;QSIWebResponsiveDialog-Layout1-SI_3F5qDwQezidzQBN_close-btn&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Close'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://siteintercept.qualtrics.com/WRSiteInterceptEngine/../WRQualtricsShared/Graphics/siteintercept/wr-dialog-close-btn-black.png' and @alt = 'Close']</value>
   </webElementXpaths>
</WebElementEntity>
