<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>go_to_top_button</name>
   <tag></tag>
   <elementGuidId>61170609-3483-4576-a67d-916584852f52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-desktop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='undefined']/div/div/button/span)[41]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-desktop</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Top </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;xs-up:bgc=body xs-up.fa-times:icon-before=cross state-loading&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;xs-up:fc=alpha xs-up:scrollable=none xs-up.icon:w=(1.875rem) xs-up.icon:h=(1.875rem) xs-up.icon:d=inblock xs-up.icon:stroke-width=(1.3867) md-up[leo-page]:px=4 lg-up[leo-page]:px=5 lg-up.LandingPage2Template>[leo-page]:px=0 xs-up.MultiStepCheckoutSummaryPageTemplate>[leo-page]:px=0 xs-up.MultiStepCheckoutSummaryPageTemplate+footer:d=none xs-up>>header>>[leo-page]:px=0 xs-up>>footer>>[leo-page]:px=0 md-up.ProductDetailsPageTemplate>[leo-page]:pr=0 xs-up>>picture:wmin=(1px) xs-up>>picture:hmin=(1px) xs-up>>picture:d=block&quot;]/cx-storefront[@class=&quot;stop-navigating&quot;]/footer[1]/cx-page-layout[@class=&quot;footer&quot;]/cx-page-slot[@class=&quot;Footer has-components&quot;]/div[1]/div[@id=&quot;undefined&quot;]/div[@class=&quot;leo-back-to-top-component leo-back-to-top-component-btn-back-to-top-alpha xs-up>>button:z=999 xs-up>>button:w=100 xs-up>>button:bgc=body xs-up>>button:bc=muted sm-down>>button:bw=0 sm-down>>button:bw-top=(1px) xs-up>>button:p=3 md-up>>button:p=0 xs-up>>button:fs=p2 md-up>>button:fs=p6 md-up>>button:bw=(1px) md-up>>button:square=(4rem) md-up>>button:pos=fix md-up>>button:right=0 md-up>>button:bottom=8 md-up>>button:txt-case=upper md-up>>button:focus:ow=(1px) md-up>>button:focus:oc=alpha md-up>>button:focus:oo=(-4px) xs-up.text-desktop>>.icon:square=(22px) xs-up.text-desktop:d=none md-up.text-desktop:flx-col-align=center-center xs-up.text-mobile>>.icon:wmax=(1.75rem) xs-up.text-mobile>>.icon:hmax=(1rem) xs-up.text-mobile>>.icon:stroke-width=(3px) xs-up.text-mobile:fw=light xs-up.text-mobile:fs=p4 xs-up.text-mobile:ls=.1 xs-up.text-mobile:txt-case=upper xs-up.text-mobile:flx-row-align=center-center xs-up.text-mobile>>[leo-icon]:flx-order=2 xs-up.text-mobile>>[leo-icon]:ml=5 sm-down.text-mobile:ml=7 md-up.text-mobile:d=none btn-back-to-top-alpha&quot;]/div[1]/button[1]/span[@class=&quot;text-desktop&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='undefined']/div/div/button/span)[41]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='file cabinets'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='office chairs'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top'])[2]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Know What', &quot;'&quot;, 's Up. Sign Up For Emails.')])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Top']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cx-page-slot/div/div/div/div/button/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Top ' or . = ' Top ')]</value>
   </webElementXpaths>
</WebElementEntity>
