<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Feedback_zoom-btn zoom-prev-btn xs-updnone</name>
   <tag></tag>
   <elementGuidId>33cc1cb9-a410-485b-9fe7-01d0463af8a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zoom-btn zoom-prev-btn xs-up:d=none</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;xs-up:bgc=body xs-up.fa-times:icon-before=cross state-loading modal-open&quot;]/ngb-modal-window[@class=&quot;d-block fade gallery-zoom-alpha leo-product-images-component leo-product-images-component-gallery-zoom-alpha md-up.thumbs-wrapper:left=(50%) md-up.thumbs-wrapper:translate-x=n50 md-up.thumbs-wrapper:w=auto md-up.zoom-wrapper:pb=0 modal modal-xxl show xs-up.grid-wrapper:flx-justify-content=center xs-up.image-gallery-container:d=flx xs-up.image-gallery-container:flx-dir=row xs-up.image-gallery-container:square=(100%) xs-up.modal-body:leri=0 xs-up.modal-body:p=0 xs-up.modal-body:pos=abs xs-up.modal-body:tobo=0 xs-up.modal-close-btn:before:fs=i3 xs-up.modal-close-btn:bgc=transparent xs-up.modal-close-btn:btn=white xs-up.modal-close-btn:bw=0 xs-up.modal-close-btn:icon-before=cross xs-up.modal-close-btn:ml=auto xs-up.modal-close-btn:p=2 xs-up.modal-close-btn:w=100 xs-up.modal-head:d=flx xs-up.modal-head:pos=abs xs-up.modal-head:right=3 xs-up.modal-head:top=3 xs-up.modal-head:w=(4rem) xs-up.modal-head:z=3 xs-up.thumbnail-media.active:bc=beta xs-up.thumbnail-media.active:bw-bottom=(0.25rem) xs-up.thumbnail-media:focus:oo=0 xs-up.thumbnail-media:focus:ow=0 xs-up.thumbnail-media:mx=(2px) xs-up.thumbnail-media:my=1 xs-up.thumbnail-media:pb=2 xs-up.thumbnail-media:w=(4.5rem) xs-up.thumbs-wrapper:bgc=body xs-up.thumbs-wrapper:bottom=3 xs-up.thumbs-wrapper:left=0 xs-up.thumbs-wrapper:pos=abs xs-up.thumbs-wrapper:scrollable=x xs-up.thumbs-wrapper:w=100 xs-up.thumbs-wrapper:z=3 xs-up.thumbs-wrapper>div:d=flx xs-up.thumbs-wrapper>div:flx-align-items=center xs-up.zoom-btn:before:fs=h5 xs-up.zoom-btn:before:fw=bold xs-up.zoom-btn:bgc=transparent xs-up.zoom-btn:bw=0 xs-up.zoom-btn:d=block xs-up.zoom-btn:outline=none xs-up.zoom-next-btn:icon-before=next xs-up.zoom-next-btn:pos-align=center-right xs-up.zoom-prev-btn:icon-before=prev xs-up.zoom-prev-btn:pos-align=center-left xs-up.zoom-wrapper:pb=8 xs-up.zoom-wrapper:square=(100%) xs-up:d=block xs-up:d=flx xs-up:flx-dir=col xs-up:hmax=100 xs-up&lt;&lt;.modal-open>>.modal-dialog:h=100 xs-up&lt;&lt;.modal-open>>.modal-dialog:m=0 xs-up&lt;&lt;.modal-open>>.modal-dialog:w=100 xs-up&lt;&lt;.modal-open>>.modal-dialog:wmax=100 xs-up>>[leo-product-images-gallery]:h=100&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[1]/div[@class=&quot;image-gallery-container&quot;]/div[@class=&quot;modal-body&quot;]/button[@class=&quot;zoom-btn zoom-prev-btn xs-up:d=none&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
   </webElementXpaths>
</WebElementEntity>
