<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SHARE_xs-upwauto xs-uphmax100 xs-upwmax100_1</name>
   <tag></tag>
   <elementGuidId>a8787f5d-55ac-4b25-8f48-08b74994072e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AllsSocialShareTwitter']/div/div/a/span/div/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/social-twitter.png?context=bWFzdGVyfGltYWdlc3wxNDc1fGltYWdlL3BuZ3xoZjEvaDZkLzk0MjMxNDMzMDUyNDYvc29jaWFsLXR3aXR0ZXIucG5nfGQ4N2YxMWI2ZTMxYTIzNGVlMTM0ZDZjYTQwNzc4YWNkMzUwNTI3YTZkNDY1YWZhMjA5ZjllYzQ0ZDgxYjkwZDQ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Twitter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AllsSocialShareTwitter&quot;)/div[@class=&quot;leo-image-link-component leo-image-link-component-link-image-social-share xs-up:w=(1.42rem) xs-up:ml=(1.42rem) link-image-social-share&quot;]/div[1]/a[@class=&quot;link&quot;]/span[@class=&quot;img-wrapper is-initialized&quot;]/div[1]/picture[1]/img[@class=&quot;xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AllsSocialShareTwitter']/div/div/a/span/div/picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Twitter']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/a/span/div/picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/social-twitter.png?context=bWFzdGVyfGltYWdlc3wxNDc1fGltYWdlL3BuZ3xoZjEvaDZkLzk0MjMxNDMzMDUyNDYvc29jaWFsLXR3aXR0ZXIucG5nfGQ4N2YxMWI2ZTMxYTIzNGVlMTM0ZDZjYTQwNzc4YWNkMzUwNTI3YTZkNDY1YWZhMjA5ZjllYzQ0ZDgxYjkwZDQ' and @alt = 'Twitter']</value>
   </webElementXpaths>
</WebElementEntity>
