<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SHARE_xs-upwauto xs-uphmax100 xs-upwmax100</name>
   <tag></tag>
   <elementGuidId>ec285f88-9233-4bd9-bb05-8f2344c70dbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AllsSocialShareFacebook']/div/div/a/span/div/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/social-facebook.png?context=bWFzdGVyfGltYWdlc3w5MDF8aW1hZ2UvcG5nfGg0My9oNTUvOTQyMzE0ODU4MDg5NC9zb2NpYWwtZmFjZWJvb2sucG5nfGQ5ZmQ1YTEyOTIyZjRhMjUxN2ViYjFlN2M4MTQxMmJmMzg3MjllMzU2M2JmNmFkZWNlMDljYThlNTBiOWUxOTE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Facebook</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AllsSocialShareFacebook&quot;)/div[@class=&quot;leo-image-link-component leo-image-link-component-link-image-social-share xs-up:w=(1.42rem) xs-up:ml=(1.42rem) link-image-social-share&quot;]/div[1]/a[@class=&quot;link&quot;]/span[@class=&quot;img-wrapper is-initialized&quot;]/div[1]/picture[1]/img[@class=&quot;xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AllsSocialShareFacebook']/div/div/a/span/div/picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Facebook']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a/span/div/picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/social-facebook.png?context=bWFzdGVyfGltYWdlc3w5MDF8aW1hZ2UvcG5nfGg0My9oNTUvOTQyMzE0ODU4MDg5NC9zb2NpYWwtZmFjZWJvb2sucG5nfGQ5ZmQ1YTEyOTIyZjRhMjUxN2ViYjFlN2M4MTQxMmJmMzg3MjllMzU2M2JmNmFkZWNlMDljYThlNTBiOWUxOTE' and @alt = 'Facebook']</value>
   </webElementXpaths>
</WebElementEntity>
