<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tap To Zoom_xs-upwauto xs-uphmax100 xs-_6cbf40</name>
   <tag></tag>
   <elementGuidId>4fc3190e-2385-4bd9-852d-9253a0e6e466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ProductImagesComponent']/div/div/div/div/div/div/div[2]/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/WD213T-5-1.jpg-convert-900x600?context=bWFzdGVyfGF6dXJlaW1hZ2VzfDEwODQzNHxpbWFnZS9qcGVnfGhmMC9oNzIvOTIxMzA0NjkxNTEwMi9XRDIxM1QtNS0xLmpwZ19jb252ZXJ0LTkwMHg2MDB8ZjViODNkNGQyYmYwMDQ5OTEwZWE3YjRjMjYxNGE4Y2YwYjZiMTJiNTlhNDdhZGI2MTBmNjZmOWI4MGViODcwZA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Lee Lace Dress</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductImagesComponent&quot;)/div[@class=&quot;leo-product-images-component leo-product-images-component-product-gallery-alpha xs-up.image-gallery-container:d=flx xs-up.image-gallery-container:h=100 xs-up.zoom-main-wrapper:w=100 xs-up.zoom-media-wrapper>>img:w=100 xs-up:h=100 xs-up.zoom-overlay-container:pos=abs xs-up.zoom-overlay-container:d=flx xs-up.zoom-overlay-container:flx-align-items=center xs-up.zoom-overlay-container:cursor=default xs-up.zoom-overlay-container:pos-align=center-center xs-up>>[leo-product-images-gallery]:h=100 xs-up:main-image-carousel-indicators:bottom=0 xs-up:main-image-carousel-indicators:txt-align=left xs-up.carousel-dot:d=block xs-up.carousel-dot:br=full xs-up.carousel-dot:w=(8px) xs-up.carousel-dot:h=(8px) xs-up.carousel-dot:bgc=beta-60 xs-up.carousel-dot.active:bgc=beta xs-up&lt;&lt;.selected-combination-disabled:grayscale=full xs-up&lt;&lt;.selected-combination-disabled:pointer-events=disabled xs-up.grid-wrapper:d=flx xs-up.grid-wrapper:flx-wrap=yes xs-up.grid-wrapper:flx-justify-content=center xs-up.grid-item:w=50 xs-up.grid-item:pb=gutter xs-up.grid-item:nth-child(2n+1):pr=gutter-half xs-up.grid-item:nth-child(2n):pl=gutter-half xs-up.zoom-overlay-container:d=block md-up.zoom-overlay-container:d=none xs-up.grid-item:hover>>.zoom-overlay-container:d=block xs-up.zoom-overlay-container>span:d=none xs-up.zoom-overlay-container:pos-align=top-right xs-up.grid-item:nth-child(2n+1)>>.zoom-overlay-container:right=5 xs-up.grid-item:nth-child(2n)>>.zoom-overlay-container:right=3 xs-up.zoom-overlay-container:top=3 xs-up.zoom-overlay-container:icon-after=zoom xs-up.main-media>>img:w=100 xs-up:gallery-images-beta md-up:product-gallery-alpha&quot;]/div[1]/div[@class=&quot;image-gallery-container&quot;]/div[@class=&quot;zoom-main-wrapper&quot;]/div[@class=&quot;grid-wrapper&quot;]/div[@class=&quot;grid-item xs-up:pos=rel main-media-wrapper0&quot;]/div[@class=&quot;main-media active is-initialized&quot;]/div[1]/picture[1]/img[@class=&quot;xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ProductImagesComponent']/div/div/div/div/div/div/div[2]/div/picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Lee Lace Dress']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/WD213T-5-1.jpg-convert-900x600?context=bWFzdGVyfGF6dXJlaW1hZ2VzfDEwODQzNHxpbWFnZS9qcGVnfGhmMC9oNzIvOTIxMzA0NjkxNTEwMi9XRDIxM1QtNS0xLmpwZ19jb252ZXJ0LTkwMHg2MDB8ZjViODNkNGQyYmYwMDQ5OTEwZWE3YjRjMjYxNGE4Y2YwYjZiMTJiNTlhNDdhZGI2MTBmNjZmOWI4MGViODcwZA' and @alt = 'Lee Lace Dress']</value>
   </webElementXpaths>
</WebElementEntity>
