<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SHARE_xs-upwauto xs-uphmax100 xs-upwmax100_1_2</name>
   <tag></tag>
   <elementGuidId>0277b927-3676-400d-90b3-e6f82471f8b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AllsSocialSharePinterest']/div/div/a/span/div/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/social-pinterest.png?context=bWFzdGVyfGltYWdlc3wyNTE2fGltYWdlL3BuZ3xoNTUvaDExLzk0MjMxNTIwODcwNzAvc29jaWFsLXBpbnRlcmVzdC5wbmd8NmMwZDc4MDM1MjI3YWY5OWM2YTc3MWZiNTQ3MjcwOWMzY2RjMzI0Y2Q5MzlhZGU0Yjg0YWY0MzRjMzNlNmEwMg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pinterest</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AllsSocialSharePinterest&quot;)/div[@class=&quot;leo-image-link-component leo-image-link-component-link-image-social-share xs-up:w=(1.42rem) xs-up:ml=(1.42rem) link-image-social-share&quot;]/div[1]/a[@class=&quot;link&quot;]/span[@class=&quot;img-wrapper is-initialized&quot;]/div[1]/picture[1]/img[@class=&quot;xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AllsSocialSharePinterest']/div/div/a/span/div/picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Pinterest']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/a/span/div/picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/social-pinterest.png?context=bWFzdGVyfGltYWdlc3wyNTE2fGltYWdlL3BuZ3xoNTUvaDExLzk0MjMxNTIwODcwNzAvc29jaWFsLXBpbnRlcmVzdC5wbmd8NmMwZDc4MDM1MjI3YWY5OWM2YTc3MWZiNTQ3MjcwOWMzY2RjMzI0Y2Q5MzlhZGU0Yjg0YWY0MzRjMzNlNmEwMg' and @alt = 'Pinterest']</value>
   </webElementXpaths>
</WebElementEntity>
