<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add to Bag_xs-upwauto xs-uphmax100 xs-u_8c39e2</name>
   <tag></tag>
   <elementGuidId>6aeee8da-555b-459f-a5e1-5f338c4a000b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='undefined']/div/div/a/div[2]/div/picture/img)[45]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/WG611U-437-2.jpg-convert-900x600?context=bWFzdGVyfGF6dXJlaW1hZ2VzfDcxMDQxfGltYWdlL2pwZWd8aDE5L2g0ZC85MTk2NDA1MjI3NTUwL1dHNjExVS00MzctMi5qcGdfY29udmVydC05MDB4NjAwfGJkODdkMmNlZjdjZjA5NGVlNDMxZmQ1MzcxZGFmNjY2M2Y2ODYzM2VlOWZjNGFkYmY2NWM5MWY1MDE5MTNlNmE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Snake Eagle Imo Boy T-Shirt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductListComponent&quot;)/div[@class=&quot;leo-product-list-component leo-product-list-component-product-grid-alpha-three-columns xs-up:product-grid:pos=rel xs-up:product-grid-col-item-inner:h=100 xs-up:ff=beta xs-up:hmin=(400px) md-up:hmin=(500px) lg-up:hmin=(700px) xs-up:product-grid-container:px=4 lg-up:product-grid-container:px=(5.5rem) lg-up:product-grid-container:wmax=100 xs-up:product-grid-row-group:mb=5 xs-up:product-grid-col-item-inner:d=flx xs-up:product-grid-col-item-inner:flx-dir=col xs-up:product-grid-col-item-inner:pos=rel xs-up:product-grid-col-item-inner:pr=0 md-up:product-grid-col-item-inner:pr=6 xs-up:product-grid-col-item-inner:pl=0 md-up:product-grid-col-item-inner:pl=0 lg-up:product-grid-col-item-inner:pl=0 xs-up.row-image+.row:mt=5 xs-up.row-image>.col-item>.col-item-inner:px=0! md-up.row-add-to-wishlist>>.col-item:hover>>.tile-add-to-wishlist:d=flx lg-up.tile-add-to-wishlist:d=none xs-up.tile-add-to-wishlist:pos-align=top-right xs-up.tile-add-to-wishlist>>.btn-wishlist:before:square=(1.333rem) xs-up.tile-add-to-wishlist:bottom=auto md-down>>.col-6>>.tile-add-to-wishlist:bottom=2 md-down>>.col-6>>.tile-add-to-wishlist:top=auto lg-up.tile-add-to-wishlist:top=n1 xs-up.tile-variant-selector-advanced>>.features-group:mb=3 xs-up.tile-variant-selected-item>>.variant-list:mb=3 xs-up.tile-name:pr=7 md-down>>.col-6>>.tile-name:pr=0 xs-up.tile-summary>>.summary:mb=3 xs-up.tile-add-to-cart:mt=auto xs-up.tile-image:d=flx xs-up.tile-image:h=100 xs-up.tile-image>div:w=100 xs-up:product-grid-alpha-two-columns lg-up:product-grid-alpha-three-columns md-down.tile-variant-selector-simple>>.size:d=none&quot;]/div[1]/div[@class=&quot;container container-grid&quot;]/div[@class=&quot;row-group&quot;]/div[@class=&quot;row row-image row-discount-badge&quot;]/div[@class=&quot;col-item col-4&quot;]/div[@class=&quot;col-item-inner&quot;]/div[@class=&quot;tile tile-image&quot;]/div[@id=&quot;undefined&quot;]/div[@class=&quot;leo-product-image-component leo-product-image-component-product-image-alpha xs-up.product-images:scrollable=none xs-up.product-images:pos=rel xs-up.product-images:cursor=pointer xs-up.product-images>>img:w=100 xs-up.product-rollover-image:w=100 xs-up.product-rollover-image:pos=abs xs-up.product-rollover-image:top=0 xs-up.product-rollover-image:left=0 xs-up.rollover>>[leo-media]:transition=opacity xs-up.rollover>>.product-rollover-image:opacity=0 xs-up.rollover.product-images:hover>>.product-image:opacity=0 xs-up.rollover.product-images:hover>>.product-rollover-image:opacity=100 xs-up:h=100 xs-up>div:h=100 xs-up.product-images.rollover:d=block xs-up.is-missing:h=100 xs-up.media-placeholder:h=100 xs-up&lt;&lt;.selected-combination-disabled:grayscale=full xs-up&lt;&lt;.selected-combination-disabled:pointer-events=disabled product-image-alpha&quot;]/div[1]/a[@class=&quot;product-images rollover&quot;]/div[@class=&quot;product-rollover-image is-initialized&quot;]/div[1]/picture[1]/img[@class=&quot;xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='undefined']/div/div/a/div[2]/div/picture/img)[45]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Snake Eagle Imo Boy T-Shirt'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[3]/div/div/div/div/div/a/div[2]/div/picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/WG611U-437-2.jpg-convert-900x600?context=bWFzdGVyfGF6dXJlaW1hZ2VzfDcxMDQxfGltYWdlL2pwZWd8aDE5L2g0ZC85MTk2NDA1MjI3NTUwL1dHNjExVS00MzctMi5qcGdfY29udmVydC05MDB4NjAwfGJkODdkMmNlZjdjZjA5NGVlNDMxZmQ1MzcxZGFmNjY2M2Y2ODYzM2VlOWZjNGFkYmY2NWM5MWY1MDE5MTNlNmE' and @alt = 'Snake Eagle Imo Boy T-Shirt']</value>
   </webElementXpaths>
</WebElementEntity>
