<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Vintage Black_xs-upwauto xs-uphmax100 x_97bc05</name>
   <tag></tag>
   <elementGuidId>ecc3df4d-f5c1-4d77-bf7c-e714e54f6d5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='undefined']/div/div/div/div/div/div/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/WG035V-839.jpg?context=bWFzdGVyfGF6dXJlaW1hZ2VzfDM4OHxpbWFnZS9qcGVnfGhlNi9oZTkvOTMzNDUzOTU4MzUxOC9XRzAzNVYtODM5LmpwZ3wyYjYwNTQwNWZiOTJiMDcwMWRkNzM1ZWMzNTE1YjQ5M2IwM2VhOTFmYjAwY2JlZTk4MDNiNmQzYmFjZTY1NzA0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductListComponent&quot;)/div[@class=&quot;leo-product-list-component leo-product-list-component-product-grid-alpha-three-columns xs-up:product-grid:pos=rel xs-up:product-grid-col-item-inner:h=100 xs-up:ff=beta xs-up:hmin=(400px) md-up:hmin=(500px) lg-up:hmin=(700px) xs-up:product-grid-container:px=4 lg-up:product-grid-container:px=(5.5rem) lg-up:product-grid-container:wmax=100 xs-up:product-grid-row-group:mb=5 xs-up:product-grid-col-item-inner:d=flx xs-up:product-grid-col-item-inner:flx-dir=col xs-up:product-grid-col-item-inner:pos=rel xs-up:product-grid-col-item-inner:pr=0 md-up:product-grid-col-item-inner:pr=6 xs-up:product-grid-col-item-inner:pl=0 md-up:product-grid-col-item-inner:pl=0 lg-up:product-grid-col-item-inner:pl=0 xs-up.row-image+.row:mt=5 xs-up.row-image>.col-item>.col-item-inner:px=0! md-up.row-add-to-wishlist>>.col-item:hover>>.tile-add-to-wishlist:d=flx lg-up.tile-add-to-wishlist:d=none xs-up.tile-add-to-wishlist:pos-align=top-right xs-up.tile-add-to-wishlist>>.btn-wishlist:before:square=(1.333rem) xs-up.tile-add-to-wishlist:bottom=auto md-down>>.col-6>>.tile-add-to-wishlist:bottom=2 md-down>>.col-6>>.tile-add-to-wishlist:top=auto lg-up.tile-add-to-wishlist:top=n1 xs-up.tile-variant-selector-advanced>>.features-group:mb=3 xs-up.tile-variant-selected-item>>.variant-list:mb=3 xs-up.tile-name:pr=7 md-down>>.col-6>>.tile-name:pr=0 xs-up.tile-summary>>.summary:mb=3 xs-up.tile-add-to-cart:mt=auto xs-up.tile-image:d=flx xs-up.tile-image:h=100 xs-up.tile-image>div:w=100 xs-up:product-grid-alpha-two-columns lg-up:product-grid-alpha-three-columns md-down.tile-variant-selector-simple>>.size:d=none&quot;]/div[1]/div[@class=&quot;container container-grid&quot;]/div[@class=&quot;row-group&quot;]/div[@class=&quot;row row-add-to-wishlist row-badges row-name row-price row-variant-selector-simple row-add-to-cart row-stock-badge-cta&quot;]/div[@class=&quot;col-item col-4&quot;]/div[@class=&quot;col-item-inner&quot;]/div[@class=&quot;tile tile-variant-selector-simple&quot;]/div[@id=&quot;undefined&quot;]/div[@class=&quot;leo-product-variant-selector-component leo-product-variant-selector-component-product-variant-selector-simple-alpha xs-up.variant-list:flx-row-align=center-left xs-up.dropdown-toggle:after:d=none xs-up:ff=alpha xs-up:mb=3 xs-up.variant-list:pos=rel xs-up.variant-list:pt=3 xs-up.variant-group-title:d=none xs-up.variant-list:flx-wrap=yes xs-up.variant-list-item:mr=2 xs-up.variant-list-item:mb=auto xs-up.btn-more:btn=body xs-up.btn-more:btn-size=small xs-up.btn-more:fw=medium xs-up.btn-more:p=0 xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:d=flx xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:py=2 xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:fs=p3 xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:fw=semi xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:fc=warning xs-up&lt;&lt;.selected-combination-disabled>>.not-combined-message:mb=3 xs-up.tooltip>>p:m=0 xs-up:product-variant-selector-simple-gamma md-up:product-variant-selector-simple-alpha&quot;]/div[1]/div[@class=&quot;variant-group&quot;]/div[@class=&quot;variant-list color&quot;]/div[@class=&quot;variant-list-item state-selected&quot;]/div[@id=&quot;undefined&quot;]/div[@class=&quot;leo-variant-item-component leo-variant-item-component-variant-item-alpha xs-up.variant-item:lh=1 xs-up.variant-item>>[leo-media]:br=0 xs-up.variant-item>>[leo-media]:bc=alpha xs-up.variant-item>>[leo-media]:bw=(1px) xs-up.variant-item>>[leo-media]:p=(1px) xs-up.variant-item>>[leo-media]:pos=rel xs-up.variant-item:pos=rel xs-up.variant-item:flx-row-align=center-center xs-up.variant-item:icon-after=none xs-up.variant-item>>img:br=0 xs-up.state-active>>.variant-item>>[leo-media]:bc=alpha xs-up.state-active>>.variant-item>>[leo-media]:bw=(2px) xs-up&lt;&lt;.size>>.state-passive>>.variant-item:fc=muted xs-up&lt;&lt;.size>>.state-passive>>.variant-item:bc=muted xs-up&lt;&lt;.size>>.state-passive>>.variant-item>>.variant-value:icon-before=icon-disabled xs-up>>.tooltip:txt-wrap=(pre) xs-up>>.out-of-stock-tooltip>.tooltip-inner:bgc=body xs-up>>.out-of-stock-tooltip>.tooltip-inner:fc=alpha xs-up>>.out-of-stock-tooltip>.tooltip-inner:fs=p3 xs-up>>.out-of-stock-tooltip>.tooltip-inner:br=0 xs-up>>.out-of-stock-tooltip>.tooltip-inner:bw=(1px) xs-up>>.out-of-stock-tooltip>.tooltip-inner:bc=muted xs-up>>.out-of-stock-tooltip>.tooltip-inner>p:px=3 xs-up>>.out-of-stock-tooltip>.tooltip-inner>p:py=2 xs-up>>.out-of-stock-tooltip>.tooltip-inner>p:m=0 xs-up>>.out-of-stock-tooltip>.tooltip-inner:opacity=100 xs-up>>.out-of-stock-tooltip>.arrow:before:bc-top=muted xs-up.state-passive>>.variant-item>>[leo-media]:before:h=(27px) xs-up.state-passive>>.variant-item>>[leo-media]:before:h=(31px) xs-up.variant-item:d=flx xs-up.variant-item:pos=static xs-up.variant-item:flx-dir=col xs-up.variant-item:flx-align-items=start xs-up.variant-item>>[leo-media]:w=(22px) xs-up.variant-item>>[leo-media]:h=(22px) md-up.variant-item>>[leo-media]:w=(26px) md-up.variant-item>>[leo-media]:h=(26px) xs-up&lt;&lt;.color>>.variant-item>>.variant-content:w=(22px) xs-up&lt;&lt;.color>>.variant-item>>.variant-content:h=(22px) md-up&lt;&lt;.color>>.variant-item>>.variant-content:w=(26px) md-up&lt;&lt;.color>>.variant-item>>.variant-content:h=(26px) xs-up&lt;&lt;.color>>.variant-item>>.variant-content:bw=(1px) xs-up&lt;&lt;.color>>.state-active>>.variant-item>>.variant-content:bw=(2px) xs-up.variant-item>>[leo-media]>>img:w=100 xs-up.variant-item>>.variant-value>>span:d=none xs-up>>.variant-item:w=auto xs-up>>.variant-item:h=(auto) xs-up>>.variant-item:bw=0 xs-up>>.variant-item:fs=p4 xs-up>>.variant-item:fw=normal xs-up>>.variant-item:mr=2 xs-up>>.variant-item:pos=rel xs-up.variant-item:wmin=(24px) xs-up.variant-item:hmax=(24px) xs-up.variant-item:h=(24px) xs-up>>.variant-item>>.variant-value:txt-wrap=no xs-up>>.variant-item>>.variant-value:fc=alpha xs-up>>.variant-item>>.variant-value:ff=beta xs-up>>.size.state-passive>>.variant-item>>.variant-value:fc=muted xs-up>>.size.state-passive>>.variant-item>>.variant-value:bc=muted xs-up>>.state-passive:not(.state-active)>>.variant-item>>.variant-value:fc=muted xs-up&lt;&lt;.size>>.variant-item:fs=p3 md-up&lt;&lt;.size>>.variant-item:fs=p2 xxl-up&lt;&lt;.size>>.variant-item:fs=p1 xs-up&lt;&lt;.size>>.variant-detail:w=100 xs-up&lt;&lt;.size>>.variant-detail:h=100 xs-up&lt;&lt;.size>>.variant-detail:d=flx xs-up&lt;&lt;.size>>.variant-detail:flx-col-align=center-center xs-up&lt;&lt;.size>>.state-active>>.variant-item>>.variant-value:bw-bottom=(1px) xs-up&lt;&lt;.color>>.variant-item>>.variant-detail:d=none xs-up&lt;&lt;.color>>.state-active>>.variant-item>>.variant-detail:d=none xs-up&lt;&lt;.color>>.variant-content:flx-row-align=center-center xs-up&lt;&lt;.color-variant-disabled>>.color.state-active.disabled>>.variant-item>>[leo-media]:bw=(2px) xs-up&lt;&lt;.color-variant-disabled>>.color.state-active.disabled>>.variant-item>>[leo-media]:bc=alpha xs-up&lt;&lt;.color-variant-disabled>>.color.state-active:not(.disabled)>>.variant-item>>[leo-media]:bw=(1px) xs-up&lt;&lt;.color-variant-disabled>>.color.state-active:not(.disabled)>>.variant-item>>[leo-media]:bc=alpha xs-up&lt;&lt;.size-variant-disabled>>.size.state-active:not(.disabled)>>.variant-item>>.variant-value:bw-bottom=(0) xs-up&lt;&lt;.size-variant-disabled>>.size.state-active.disabled>>.variant-item>>.variant-value:bw-bottom=(1px) xs-up&lt;&lt;.size-variant-disabled>>.size.state-active.disabled>>.variant-item>>.variant-value:bc=beta xs-up&lt;&lt;.size-variant-disabled>>.size.state-active.state-passive:not(.disabled)>>.variant-item:icon-before=icon-disabled xs-up&lt;&lt;.size-variant-disabled>>.size.state-active.state-passive:not(.disabled)>>.variant-value:fc=muted variant-item-alpha&quot;]/div[1]/div[@class=&quot;variant-item-container xs-up:cursor=pointer state-active color&quot;]/div[@class=&quot;variant-item&quot;]/div[@class=&quot;is-initialized&quot;]/div[1]/picture[1]/img[@class=&quot;xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='undefined']/div/div/div/div/div/div/picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/WG035V-839.jpg?context=bWFzdGVyfGF6dXJlaW1hZ2VzfDM4OHxpbWFnZS9qcGVnfGhlNi9oZTkvOTMzNDUzOTU4MzUxOC9XRzAzNVYtODM5LmpwZ3wyYjYwNTQwNWZiOTJiMDcwMWRkNzM1ZWMzNTE1YjQ5M2IwM2VhOTFmYjAwY2JlZTk4MDNiNmQzYmFjZTY1NzA0')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/WG035V-839.jpg?context=bWFzdGVyfGF6dXJlaW1hZ2VzfDM4OHxpbWFnZS9qcGVnfGhlNi9oZTkvOTMzNDUzOTU4MzUxOC9XRzAzNVYtODM5LmpwZ3wyYjYwNTQwNWZiOTJiMDcwMWRkNzM1ZWMzNTE1YjQ5M2IwM2VhOTFmYjAwY2JlZTk4MDNiNmQzYmFjZTY1NzA0']</value>
   </webElementXpaths>
</WebElementEntity>
