<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Price (lowest first)</name>
   <tag></tag>
   <elementGuidId>4169d080-4490-4d84-8ff9-8cdb41e742e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[15]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Price (lowest first)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Cb2FlexSortProductList&quot;)/div[@class=&quot;leo-product-search-sort-component leo-product-search-sort-component-product-search-sort-alpha xs-up[leo-product-search-sort]:flx-row-align=top-right xs-up&lt;&lt;.SearchResultsProductLeftRefinementsContainer>>.total-item-count:d=none md-up.total-item-count:mb=3 sm-down.total-item-count:pl=1 xs-up.total-item-count:fs=p5 xs-up.total-item-count:ls=.1 xs-up.total-item-count:lh=1 xs-up.total-item-count:fw=light xs-up.total-item-count:txt-case=upper xs-up.total-item-count:txt-wrap=no xs-up.dropdown:lh=1 sm-down.dropdown:w=100 xs-up.dropdown>>span:d=none sm-down.btn-dropdown-toggle:w=100 xs-up.btn-dropdown-toggle:btn=body xs-up.btn-dropdown-toggle:btn-size=small xs-up.btn-dropdown-toggle:fw=normal xs-up.btn-dropdown-toggle:p=0 xs-up.btn-dropdown-toggle:bgc=transparent xs-up.btn-dropdown-toggle:bc=transparent md-up.btn-dropdown-toggle:mb=3 xs-up.btn-dropdown-toggle:mr=0 xs-up.btn-dropdown-toggle:ml=3 xl-up.btn-dropdown-toggle:ml=5 xs-up.btn-dropdown-toggle:icon-after=chevron-down xs-up.btn-dropdown-toggle:after:ml=2 xs-up.btn-dropdown-toggle:after:fw=bold! xs-up.btn-dropdown-toggle:after:b=none xs-up.btn-dropdown-toggle:focus:outline=none sm-down.btn-dropdown-toggle:d=none sm-down&lt;&lt;.state-filter-open:mb=3 sm-down&lt;&lt;.state-filter-open>>.btn-dropdown-toggle:bc=alpha sm-down&lt;&lt;.state-filter-open>>.btn-dropdown-toggle:d=inflx sm-down&lt;&lt;.state-filter-open>>.btn-dropdown-toggle:ml=0 sm-down&lt;&lt;.state-filter-open>>.btn-dropdown-toggle:flx-row-align=center-between sm-down&lt;&lt;.state-filter-open>>.btn-dropdown-toggle:hmin=(3rem) sm-down&lt;&lt;.state-filter-open>>.btn-dropdown-toggle:fs=p2 sm-down&lt;&lt;.state-filter-open>>.btn-dropdown-toggle:fw=light sm-down&lt;&lt;.state-filter-open>>.btn-dropdown-toggle:px=(1.25rem) sm-down&lt;&lt;.state-filter-open>>.btn-dropdown-toggle:py=1 sm-down&lt;&lt;.state-filter-open>>.dropdown>>span:d=flx sm-down&lt;&lt;.state-filter-open>>.dropdown>>span:fs=p3! sm-down&lt;&lt;.state-filter-open>>.dropdown>>span:pb=3 sm-down&lt;&lt;.state-filter-open>>.dropdown>>span:mb=2 sm-down&lt;&lt;.state-filter-open>>.dropdown>>span:txt-case=upper sm-down.dropdown-menu:w=100 xs-up.dropdown-menu:py=0 xs-up.dropdown-menu:br=0 xs-up.dropdown-menu:bw=(1px) xs-up.dropdown-menu:bc=alpha xs-up.dropdown-item:py=3 xs-up.dropdown-item.state-active:bgc=light sm-down&lt;&lt;.state-filter-open>>.total-item-count:d=none xs-up:none md-up:product-search-sort-alpha&quot;]/div[1]/div[@class=&quot;show dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/button[@class=&quot;dropdown-item&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[15]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Cb2FlexSortProductList']/div/div/div[2]/div/button[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name (descending)'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name (ascending)'])[1]/following::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price (highest first)'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Runway White Lacquer Desk'])[1]/preceding::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Price (lowest first)']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Price (lowest first)' or . = 'Price (lowest first)')]</value>
   </webElementXpaths>
</WebElementEntity>
