<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>home_breadcrumb</name>
   <tag></tag>
   <elementGuidId>7818613b-558f-4929-a0fc-a4673516cd9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Cb2MyAccountBreadcrumbComponent']/div/div/div/div/div/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Cb2MyAccountBreadcrumbComponent&quot;)/div[@class=&quot;leo-breadcrumb-component leo-breadcrumb-component-breadcrumb-alpha xs-up:fc=mid xs-up:fs=(11px) xs-up:txt-case=upper xs-up:pos=rel xs-up:ls=.06 xs-up:z=1 xs-up.container:my=4 xs-up>>ul:list-style=none xs-up>>ul:flx-row-align=center-left xs-up>>ul:flx-wrap=yes xs-up>>li:fw=light xs-up>>li:not(:first-child):icon-before=slash-right xs-up>>li:before:fs=(17px)! xs-up>>li:before:fw=bold! xs-up>>li:before:px=(0.625rem) xs-up>>a:fc=mid xs-up>>a:hover:txt-underline=yes xl-up.static-page-template>>.container:wmax=normal xs-up.static-page-template>>h1:d=none md-down.account-page-template:d=none xl-up.account-page-template>>.container:wmax=normal xl-up.register-page-template>>.container:wmax=normal xs-up.static-page-template-about-us:d=none xs-up.landing-page2-template:d=none xs-up.login-page-template:d=none xs-up.cart-page-template:d=none xs-up.search-results-list-page-template:d=none md-down.category-page-template:d=none md-down.category-page-level1-template:d=none md-down.category-page-level2-template:d=none xs-up.category-page-level2-template:mx=(-0.25rem) md-down.product-details-page-template:d=none xs-up.product-details-page-template>>.container:px=0 xs-up.product-details-page-template>>.row:mx=0 xs-up.product-details-page-template>>.col-12:px=0 xs-up.category-page-template>>.container:px=0 xs-up.category-page-template>>.container:mb=0 xs-up.category-page-template>>.row:mx=0 xs-up.category-page-template>>.col-12:px=0 breadcrumb-alpha&quot;]/div[1]/div[@class=&quot;account-page-template account-page-template-my-account-wishlist&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/ul[1]/li[1]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Cb2MyAccountBreadcrumbComponent']/div/div/div/div/div/div/ul/li/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Home')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collaborations'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GIFTS'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[1]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en')])[21]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en' and (text() = 'Home' or . = 'Home')]</value>
   </webElementXpaths>
</WebElementEntity>
