<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>privacy_policy_section_footer</name>
   <tag></tag>
   <elementGuidId>06c6facc-a09a-4b43-9bdb-446bf9ab307d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Cb2NavCopyrightBottomComponent']/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>media-body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>©2021 CB2Privacy PolicyTerms of Use</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Cb2NavCopyrightBottomComponent&quot;)/div[@class=&quot;leo-advanced-content-navigation-component leo-advanced-content-navigation-component-copyright-beta xs-up:fs=p4 xs-up:fw=light xs-up:mt=1 md-down.media:flx-dir=col xs-up.nav-nodes:d=flx xs-up.nav-nodes:flx-wrap=yes md-down.nav-nodes:flx-dir=col md-up.nav-nodes>>ul:my=0 sm-up.nav-nodes>>ul:m=0 sm-up.nav-nodes>>ul:d=inflx xs-up.nav-nodes>>li:d=flx sm-up.nav-nodes>>li:d=inflx xs-up.nav-nodes>>li:mb=1 sm-up.nav-nodes>>li:mb=0 sm-up.nav-nodes>>li:mx=2 xs-up.media-item>>img:hmax=(2rem) xs-up.media-item:mx=0 xs-up.media-item:w=100 md-up.media-item:wmax=25 md-down.media-item:mb=3 xs-up.media-body:d=flx md-up.media-body:flx-justify-content=center md-down.media-body:flx-col-align-self=top-left md-down.tagline:d=block md-up.tagline:mt=0 xs-up.tagline:ls=.08 xs-up.link:ls=.06 copyright-beta&quot;]/div[1]/div[1]/div[@class=&quot;wrapper-card xs-up:card-align=center-left xs-up:card-media-align=center-left xs-up:card-content-align=center-left&quot;]/div[@class=&quot;media&quot;]/div[@class=&quot;media-body&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Cb2NavCopyrightBottomComponent']/div/div/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie Settings'])[1]/following::div[20]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Brands'])[1]/following::div[55]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '©2021 CB2Privacy PolicyTerms of Use' or . = '©2021 CB2Privacy PolicyTerms of Use')]</value>
   </webElementXpaths>
</WebElementEntity>
