<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cart_items_counter</name>
   <tag></tag>
   <elementGuidId>57515cdb-cb96-4bfb-b728-43b119a1a2d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CartHeaderComponent']/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.cart-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-header</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cart:  (1 items)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CartHeaderComponent&quot;)/div[@class=&quot;leo-cart-header-component leo-cart-header-component-cart-header md-up:mx=0 xs-up:mx=n-gutter-half xs-up.cart-header:bc-bottom=black-60 xs-up.cart-header:bw-bottom=(1px) md-up.cart-header:bw-bottom=0 xs-up.cart-header:fs=p2 md-up.cart-header:fs=h5 xs-up.cart-header:txt-case=upper xs-up.cart-header:mt=4 md-up.cart-header:mt=5 xs-up.cart-header:mb=0 xs-up.cart-header:pb=3 xs-up.cart-header:px=(20px) md-up.cart-header:px=0 xs-up.cart-total-item-count:fc=mid xs-up.cart-total-item-count:fw=light xs-up.cart-total-item-count:txt-case=lower cart-header&quot;]/div[1]/h1[@class=&quot;cart-header&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CartHeaderComponent']/div/div/h1</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collaborations'])[1]/following::h1[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GIFTS'])[1]/following::h1[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cart:']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = ' Cart:  (1 items)' or . = ' Cart:  (1 items)')]</value>
   </webElementXpaths>
</WebElementEntity>
