<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>donate_to_help_section</name>
   <tag></tag>
   <elementGuidId>ab01d482-aa9d-4403-9313-508850ea03d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Cb2CartDonationComponent']/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mt-2.tab-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-2 tab-content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Donate to help children in our communityJoin us this month in defining what ‘happiness’ means to every child here in the UAE. Let’s make their ‘happy moments’ truly ‘great moments’ not access to basics…. AED 100.00  AED 120.00  AED 130.00  AED 140.00  AED 150.00 </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Cb2CartDonationComponent&quot;)/div[@class=&quot;leo-product-carousel-component leo-product-carousel-component-product-donation-component xs-up.charity-wrapper:bw-bottom=(2px) xs-up.charity-wrapper:pb=5 xs-up.charity-wrapper:mb=5 xs-up.charity-title:d=none xs-up.charity-description:mt=3 xs-up.charity-description>>p:mb=0 xs-up.nav-tabs:d=none xs-up.nav-item:bw=(1px) xs-up.nav-item:not(:last-child):bw-right=(0) xs-up.sub-charity-info-wrapper:d=flx md-down.sub-charity-info-wrapper:flx-wrap=yes xs-up.sub-charity-logo:mr=3 xs-up.charity-logo:w=(9rem) md-up.charity-logo:w=(12rem) xl-up.charity-logo:w=(11rem) md-down.sub-charity-logo:w=100 md-down.sub-charity-logo:mb=2 xs-up.sub-charity-title:fw=normal xs-up.tab-content:px=0 xs-up.charity-content:bw=(1px) xs-up.charity-content:p=3 xs-up.btn-donate:hmin=(40px) xs-up.btn-donate:px=(3rem) xs-up.btn-donate:mt=4 xs-up.btn-apply:mr=4 xs-up.sub-charity-amounts:d=flx xs-up.sub-charity-amounts:flx-wrap=yes xs-up.sub-charity-amounts:mt=3 xs-up.sub-charity-amounts:mx=n2 md-down.sub-charity-amounts:flx-justify-content=between xs-up.btn-amount:mx=2 xs-up.btn-amount:wmin=15 xs-up.btn-amount:py=1 xs-up.btn-amount:px=3 xs-up.btn-amount:fw=bold xs-up.btn-amount:mb=3 xs-up.apply-donation-error:fc=danger xs-up.apply-donation-error:m=0 xs-up.apply-donation-error:p=0 xs-up.apply-donation-error:pos=rel product-donation-component&quot;]/div[1]/div[@class=&quot;charity-wrapper&quot;]/div[@class=&quot;charity-content&quot;]/div[@class=&quot;mt-2 tab-content&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Cb2CartDonationComponent']/div/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHARE'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donate to help children in our community'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/cx-page-slot/div[3]/div/div/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Donate to help children in our communityJoin us this month in defining what ‘happiness’ means to every child here in the UAE. Let’s make their ‘happy moments’ truly ‘great moments’ not access to basics…. AED 100.00  AED 120.00  AED 130.00  AED 140.00  AED 150.00 ' or . = 'Donate to help children in our communityJoin us this month in defining what ‘happiness’ means to every child here in the UAE. Let’s make their ‘happy moments’ truly ‘great moments’ not access to basics…. AED 100.00  AED 120.00  AED 130.00  AED 140.00  AED 150.00 ')]</value>
   </webElementXpaths>
</WebElementEntity>
