<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Clothing</name>
   <tag></tag>
   <elementGuidId>f86089a3-e4a9-43f5-8890-7922d36d3773</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AllsBreadcrumbComponent']/div/div/div/div/div/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-ae/c/women/women-clothing</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clothing</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AllsBreadcrumbComponent&quot;)/div[@class=&quot;leo-breadcrumb-component leo-breadcrumb-component-breadcrumb-alpha xs-up:fs=p4 xs-up:pos=rel xs-up:z=1 xs-up.container:my=4 xs-up>>ul:list-style=none xs-up>>ul:flx-row-align=center-left xs-up>>ul:flx-wrap=yes xs-up>>li:not(:first-child):icon-before=slash-right xs-up>>li:fc=beta xs-up>>li:before:fc=dark xs-up>>li:before:px=(0.34rem) xs-up>>li[itemscope]:txt-case=upper xs-up>>a:fc=alpha xs-up>>a:hover:txt-underline=no xs-up>>h1:fs=h3 xs-up>>h1:ls=.6 xs-up>>h1:lh=(1.1) xs-up>>h1:ff=beta xs-up>>h1:fw=light xs-up>>h1:mt=5 xs-up>>h1:mb=4 xs-up>>h1:txt-align=center xs-up.static-page-template>>ul:d=none xs-up.static-page-template>>.container:wmax=normal xs-up.account-page-template:d=none xs-up.register-page-template:d=none xs-up.static-page-template-about-us:d=none xs-up.landing-page2-template:d=none xs-up.login-page-template:d=none xs-up.cart-page-template:d=none xs-up.search-results-list-page-template:d=none xs-up.content-page1-template>>h1:d=none xs-up.category-page-level1-template:d=none xs-up.error-page-template:d=none xs-up.store-finder-page-template:d=none xs-up.static-page-template-all:d=none xs-up.static-page-template-women-beta:d=none xs-up.static-page-template-men-beta:d=none xs-up.static-page-template-features:d=none xs-up.static-page-template-not-for-sale:d=none xs-up.product-list-page-template>>.container:wmax=100 xs-up.product-list-page-template>>.container:px=(1.3rem) md-up.product-list-page-template>>.container:px=(2.3rem) xs-up.static-page-template-guest-order:ff=beta xs-up.static-page-template-guest-order:py=3 xs-up.static-page-template-guest-order>>h1:ls=.4 xs-up.product-details-page-template:px=2 xs-up.static-page-template-features-denim-guide:d=none breadcrumb-alpha xs-up.product-list-page-template:d=block!&quot;]/div[1]/div[@class=&quot;product-details-page-template product-details-page-template-product-details&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/ul[1]/li[3]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AllsBreadcrumbComponent']/div/div/div/div/div/div/ul/li[3]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Clothing')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Women'])[4]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Women'])[3]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clothing'])[3]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lee Lace Dress'])[1]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en-ae/c/women/women-clothing')])[12]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en-ae/c/women/women-clothing' and (text() = 'Clothing' or . = 'Clothing')]</value>
   </webElementXpaths>
</WebElementEntity>
