<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add to favorites_share-logo xs-upmrauto_34568e</name>
   <tag></tag>
   <elementGuidId>07d5a163-65d8-43a9-9d5e-35986b05f40b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EarnablePointsComponent']/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>share-logo xs-up:mr=auto xs-up:mb=2 xs-up:wmax=100 md-down:mx=auto</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./assets/images/maf-share.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EarnablePointsComponent&quot;)/div[@class=&quot;leo-earnable-points-component leo-earnable-points-component-product-earnable-points xs-up&lt;&lt;.selected-variant-option-disabled:d=none xs-up.image-container:w=(8.5rem) xs-up.image-container:flx-align-items=center xs-up.earnable-points-for-product:fs=p3 lg-up.earnable-points-for-product:fs=p1 xs-up.earnable-points-for-product:fw=semi xs-up.earnable-points-for-product:fc=burgundy xs-up.earnable-points-for-product:bc=muted xs-up.icon-info:icon-before=question-mark xs-up.icon-info:invert=(0.4) product-earnable-points&quot;]/div[1]/div[@class=&quot;share-earnable-points xs-up:d=flx xs-up:mb=3&quot;]/div[@class=&quot;image-container xs-up:d=flx xs-up:w=30 xs-up:pr=3&quot;]/img[@class=&quot;share-logo xs-up:mr=auto xs-up:mb=2 xs-up:wmax=100 md-down:mx=auto&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EarnablePointsComponent']/div/div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './assets/images/maf-share.png']</value>
   </webElementXpaths>
</WebElementEntity>
