<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product_with_discount</name>
   <tag></tag>
   <elementGuidId>624ec885-ae4f-41b5-85bf-16b3804b4f21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ProductListComponent']/div/div/div/div[9]/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-item col-3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductListComponent&quot;)/div[@class=&quot;leo-product-list-component leo-product-list-component-product-grid-alpha-four-columns xs-up:product-grid:pos=rel xs-up:product-grid-col-item-inner:h=100 xs-up:product-grid-container:px=0 xs-up:product-grid-row-group:mb=5 xs-up:product-grid-col-item-inner:pos=rel xs-up.row-badges>.col-item>.col-item-inner:d=flx xs-up:product-grid-col-item-inner:pr=6 xs-up.row-image+.row:mt=gutter-half xs-up.row-image>.col-item>.col-item-inner:px=0! xs-up.row-price>>.col-item-inner:flx-col-align=top-left xs-up.row-price>>.col-item-inner>>.tile-price:flx=fill xs-up.tile-add-to-wishlist:pos=abs xs-up.tile-add-to-wishlist:right=n1 xs-up.tile-add-to-wishlist:top=n1 xs-up.tile-variant-selector-simple>>.variant-group:mb=3 xs-up.tile-variant-selector-advanced>>.features-group:mb=3 xs-up.tile-variant-selected-item>>.variant-list:mb=3 xs-up.tile-name>>.name:mb=2 xs-up.tile-summary>>.summary:mb=3 xs-up.tile-price+.tile:mt=3 xs-up.tile-stock-badge-cta:mt=0! xs-up.tile-stock-badge-cta:flx=fill xs-up.tile-stock-badge-cta+.tile:mt=3 xs-up:product-grid-alpha-two-columns md-up:product-grid-alpha-three-columns lg-up:product-grid-alpha-two-columns xl-up:product-grid-alpha-three-columns xxl-up:product-grid-alpha-four-columns&quot;]/div[1]/div[@class=&quot;container container-grid&quot;]/div[@class=&quot;row-group&quot;]/div[@class=&quot;row row-image&quot;]/div[@class=&quot;col-item col-3&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ProductListComponent']/div/div/div/div[9]/div/div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[25]/following::div[34]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fullerton Modular Desk with 2 Drawers'])[1]/preceding::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to favorites'])[33]/preceding::div[14]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[4]</value>
   </webElementXpaths>
</WebElementEntity>
