<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Face Masks_xs-upwauto xs-uphmax100 xs-u_dc2b8c</name>
   <tag></tag>
   <elementGuidId>3ec99e52-817d-4c87-bc44-92410ecc495c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AllsImageLinkAllDayAllNightWomen']/div/div/a/span/div/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/AS-FW10.21-P1-Women-Menu.jpg?context=bWFzdGVyfHJvb3R8MTg0NzU0fGltYWdlL2pwZWd8aGRkL2hiOC85NDIzMTQ3NzI4OTI2L0FTX0ZXMTAuMjFfUDFfV29tZW5fTWVudS5qcGd8YzIxMjJkMGVmMzkzYzBjMTgxYzljMzU5NmZiYjljNmE1ZjdlZmM0MmE5MWZiNTM4NzlmMTY5YjZhMWJmYTJlOA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>AS_FW10.21_P1_Women_Menu.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AllsImageLinkAllDayAllNightWomen&quot;)/div[@class=&quot;leo-image-link-component leo-image-link-component-link-image-default xs-up>>img:w=100 link-image-default&quot;]/div[1]/a[@class=&quot;link&quot;]/span[@class=&quot;img-wrapper is-initialized&quot;]/div[1]/picture[1]/img[@class=&quot;xs-up:w=auto xs-up:hmax=100 xs-up:wmax=100&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AllsImageLinkAllDayAllNightWomen']/div/div/a/span/div/picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='AS_FW10.21_P1_Women_Menu.jpg']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.c1xjddw2-majidalfu1-s1-public.model-t.cc.commerce.ondemand.com/medias/AS-FW10.21-P1-Women-Menu.jpg?context=bWFzdGVyfHJvb3R8MTg0NzU0fGltYWdlL2pwZWd8aGRkL2hiOC85NDIzMTQ3NzI4OTI2L0FTX0ZXMTAuMjFfUDFfV29tZW5fTWVudS5qcGd8YzIxMjJkMGVmMzkzYzBjMTgxYzljMzU5NmZiYjljNmE1ZjdlZmM0MmE5MWZiNTM4NzlmMTY5YjZhMWJmYTJlOA' and @alt = 'AS_FW10.21_P1_Women_Menu.jpg']</value>
   </webElementXpaths>
</WebElementEntity>
