<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Price (lowest first)</name>
   <tag></tag>
   <elementGuidId>2cbd7968-3827-4be4-9a37-ca5c45bb1a8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.dropdown-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Price (lowest first)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AllsFlexSortForLeftRefinement&quot;)/div[@class=&quot;leo-product-search-sort-component leo-product-search-sort-component-product-search-sort-alpha lg-up:mb=1 lg-up:bw-left=(1px) lg-up:bc=muted lg-up:ml=4 lg-up:pl=5 xs-up[leo-product-search-sort]:flx-row-align=center-center xs-up.dropdown:pos=static xs-up.dropdown:w=100 xs-up.dropdown-menu:w=100 lg-up.dropdown-menu:w=auto xs-up.dropdown-menu:left=(-0.8rem)! xs-up.dropdown-menu:top=(4px)! lg-up.dropdown-menu:left=0! xs-up.btn-dropdown-toggle:btn=body xs-up.btn-dropdown-toggle:btn-size=small xs-up.btn-dropdown-toggle:w=100 lg-up.btn-dropdown-toggle:w=auto xs-up.btn-dropdown-toggle:bgc=transparent xs-up.btn-dropdown-toggle:bc=transparent lg-up.btn-dropdown-toggle:fw=medium xs-up.btn-dropdown-toggle:txt-case=upper xs-up.btn-dropdown-toggle:p=0 xs-up.btn-dropdown-toggle:my=0 xs-up.btn-dropdown-toggle:mr=0 xs-up.btn-dropdown-toggle:hmin=(30px) lg-up.btn-dropdown-toggle:icon-after=chevron-down xs-up.btn-dropdown-toggle:after:ml=2 xs-up.btn-dropdown-toggle:after:b=none xs-up.dropdown-menu:py=0 xs-up.dropdown-menu:br=0 xs-up.dropdown-menu:bw=(1px) xs-up.dropdown-menu:bc=alpha xs-up.dropdown-item:py=3 xs-up.dropdown-item.state-active:bgc=light xs-up:none lg-up:product-search-sort-alpha&quot;]/div[1]/div[@class=&quot;show dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/button[@class=&quot;dropdown-item&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[13]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AllsFlexSortForLeftRefinement']/div/div/div/div/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relevance'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[4]/following::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price (highest first)'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relevance'])[2]/preceding::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Price (lowest first)']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Price (lowest first)' or . = 'Price (lowest first)')]</value>
   </webElementXpaths>
</WebElementEntity>
