<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_input_homepage</name>
   <tag></tag>
   <elementGuidId>885f49b7-32ca-40c8-b29b-92d3f9ccd9b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.mobile-placeholder.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mobile-placeholder ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchBox&quot;)/div[@class=&quot;leo-search-box-component leo-search-box-component-search-alpha xs-up.wrapper:pos=rel xs-up.dropdown-menu.show:w=100 xs-up:hover:bgc=light xs-up.search-box-wrapper:bgc=gray-100 xs-up.search-box-wrapper:float=left xs-up.search-box-wrapper:hmin=(2rem) xs-up.search-box-wrapper:p=3 xs-up.search-box-wrapper:pos=rel md-up.search-box-wrapper:bgc=white md-up.search-box-wrapper:my=2 md-up.search-box-wrapper:p=0 xs-up.search-box-wrapper>>.dropdown-item:p=0 xs-up.search-box-wrapper>>.dropdown-item-wrapper:px=3 xs-up.search-box-wrapper>>.dropdown-item-wrapper:py=2 xs-up.search-box-wrapper>>.dropdown-item-content:cursor=pointer xs-up.search-text:d=none xs-up.form-control:mb=0 xs-up.form-control:pl=3 xs-up.form-control:pr=5 xs-up.form-control:py=1 xs-up.form-control:h=auto xs-up.form-control:fs=p2 xs-up.form-control:fw=light xs-up.form-control::placeholder:fc=muted xs-up.form-control:b=none xs-up.form-control:bw-bottom=(1px) md-up.form-control:transition=all md-up.form-control:w=(190px) xs-up.form-control:focus:bs=none md-up.state-active>>.form-control:w=(250px) lg-up.state-active>>.form-control:w=(400px) md-up.state-active>>.header-search-icon:w=(35px) md-up.state-active>>.header-search-icon:left=(220px) lg-up.state-active>>.header-search-icon:left=(365px) md-up.state-active>>.header-search-icon:pointer-events=active xs-up.header-search-icon:transition=all xs-up.header-search-icon:pointer-events=disabled xs-up.header-search-icon:opacity=100! xs-up.header-search-icon:bgc=body xs-up.header-search-icon:w=100 xs-up.header-search-icon:b=none xs-up.header-search-icon:pos=abs xs-up.header-search-icon:p=0 xs-up.header-search-icon:top=(-3px) xs-up.header-search-icon:left=0 xs-up.header-search-icon>>.icon:w=(35px) xs-up.header-search-icon>>.icon:h=(35px) xs-up.underline:d=none md-up.underline:d=block xs-up.underline:icon-after=underline-left-to-right xs-up.state-active>>.underline:icon-after=underline-left-to-right-scale xs-up.dropdown-menu:br=0 xs-up.dropdown-menu:mt=0 xs-up.dropdown-item:first-child:d=none xs-up.dropdown-item:fw:light xs-up.dropdown-item.active:cursor=default xs-up.dropdown-item.active:bgc=transparent xs-up.dropdown-item.active:fc=black xs-up:search-delta md-up:search-alpha&quot;]/div[1]/div[@class=&quot;search-box-wrapper&quot;]/div[@class=&quot;wrapper&quot;]/input[@class=&quot;form-control mobile-placeholder ng-untouched ng-pristine ng-valid&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SearchBox']/div/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search']</value>
   </webElementXpaths>
</WebElementEntity>
