<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CHECKOUT</name>
   <tag></tag>
   <elementGuidId>5121a0f6-b22e-4d06-a47f-b0c4076e41d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.user-menu-wrapper.state-mini.state-user.state-not-empty.state-modal-open > div.user-menu-dropdown > button.btn-cta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='undefined']/div/div/div/div[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-cta</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECKOUT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;xs-up:bgc=body xs-up.fa-times:icon-before=cross modal-open&quot;]/ngb-modal-window[@class=&quot;d-block fade modal modal-product-added-to-cart show xs-up:d=flx&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[1]/div[1]/div[@id=&quot;undefined&quot;]/div[@class=&quot;leo-cart-product-added-component leo-cart-product-added-component-leo-cart-product-added-component-default xs-up:pos=rel xs-up:p=2 xs-up.user-mennu-link:d=flx xs-up.user-menu-link:pos=rel xs-up.user-menu-link:txt-case=upper xs-up.user-menu-link:fs=p4 xs-up.user-menu-link:ls=.1 xs-up.user-menu-link:fw=medium xs-up.user-menu-link:icon-after=underline-left-to-right xs-up.user-menu-link:after:bw-bottom=(1px) xs-up.user-menu-link:after:d=block xs-up.user-menu-link:after:mt=(2px) xs-up.user-menu-link:after:bottom=n2 xs-up.user-menu-link:hover:txt-underline=no xs-up.user-menu-link:hover:icon-after=underline-left-to-right-scale xs-up.user-menu-link:txt-underline=no xs-up.user-menu-link:flx-row-align=center-center xs-up.user-menu-text:flx-row-align=center-center sm-down.user-menu-text:d=none md-up.user-menu-link>[leo-icon]:d=none xs-up.user-menu-link>[leo-icon]:pos=rel xs-up.user-menu-link>[leo-icon]:after:content=() xs-up.user-menu-link>[leo-icon]:after:bc=alpha xs-up.user-menu-link>[leo-icon]:after:bw-bottom=(0.25rem) xs-up.user-menu-link>[leo-icon]:after:pt=2 xs-up.user-menu-link>[leo-icon]:after:bottom=n2 xs-up.user-menu-link>[leo-icon]:after:d=none xs-up.user-menu-link>[leo-icon]:after:pos=abs xs-up.user-menu-link>[leo-icon]:after:right=0 xs-up.user-menu-link>[leo-icon]:after:w=100 xs-up.user-menu-dropdown:bw-left=(.5px) xs-up.user-menu-dropdown:bc=alpha-20 xs-up.user-menu-dropdown:bgc=body xs-up.user-menu-dropdown:p=4 xs-up.user-menu-dropdown:flx-dir=col md-up&lt;:hover>>.user-menu-link>[leo-icon]:after:d=block xs-up.state-modal-open>>.user-menu-dropdown:d=flx! md-up&lt;&lt;.modal-dialog>>.state-modal-open>>.modal-backdrop:d=none md-up.state-modal-open>>.modal-backdrop:d=block md-up.state-modal-open>>.modal-backdrop:bgc=white md-up.state-modal-open>>.modal-backdrop:opacity=80 xs-up.content:not(:last-child):mb=4 xs-up.content>>a:txt-underline=yes xs-up.btn-cta:btn=alpha xs-up.btn-cta:w=100 xs-up.btn-cta:mb=3 xs-up.btn-cta:h=(3.34rem) xs-up.more-items-text:txt-align=center xs-up.user-menu-dropdown:d=none xs-up.user-menu-dropdown:fs=p3 xs-up.user-menu-dropdown:pos=fix xs-up.user-menu-dropdown:top=0 xs-up.user-menu-dropdown:right=0 md-down.user-menu-dropdown:left=0 xs-up.user-menu-dropdown:w=100 lg-up.user-menu-dropdown:w=(33.4rem) xs-up.user-menu-dropdown:h=100 xs-up.user-menu-dropdown:px=6 xs-up.user-menu-dropdown:pt=0 xs-up.user-menu-dropdown:pb=3 xs-up.user-menu-dropdown:z=9999 xs-up.headline:fs=(28px) xs-up.headline:ff=beta xs-up.headline:bw-bottom=(1px) xs-up.headline:lh=(60px) xs-up.headline:ls=.08 xs-up.content:d=none xs-up.close:p=0 xs-up.close:m=0 xs-up.close:pos=abs xs-up.close:top=(1.75rem) xs-up.close:right=6 xs-up.close:opacity=100! xs-up.close>span:d=none xs-up.close:icon-before=remove xs-up.close:before:square=(23px) xs-up.products:flx=fill xs-up.products:scrollable=y xs-up.product:py=7 xs-up.product:bc-bottom=black xs-up.product:not(:last-child):bw-bottom=(1px) xs-up.cart-item-read-only-product:hover:txt-underline=no xs-up.cart-item-read-only-product:flx-row-align=top-between xs-up.cart-item-read-only-product:pointer-events=disabled xs-up.cart-item-read-only-product-info:pr=3 xs-up.cart-item-read-only-product-name:fs=p1 xs-up.cart-item-read-only-product-name:ff=beta xs-up.cart-item-read-only-product-name:ls=.06 xs-up.cart-item-read-only-product-image>>img:wmax=(10rem) xs-up.cart-item-read-only-product-image>>img:wmin=(10rem) xs-up.cart-item-read-only-product-image:flx-order=2 xs-up.cart-item-read-only-product-info:flx-order=1 xs-up.cart-item-read-only-product-info:d=flx xs-up.cart-item-read-only-product-info:flx-dir=col xs-up.cart-item-read-only-product-info:flx-align-items=start xs-up.price:fs=p1 xs-up.price:ff=beta xs-up.price:ls=.06 xs-up.price:mb=3 xs-up.size-variant:txt-case=upper xs-up.size-variant:fs=p4 xs-up.size-variant:ls=.08 xs-up.size-variant:mb=1 xs-up.quantity:txt-case=upper xs-up.quantity:fs=p4 xs-up.quantity:ls=.08 xs-up.quantity:mb=3 xs-up.btn-remove:bgc=transparent xs-up.btn-remove:bw=0 xs-up.btn-remove:px=0 xs-up.btn-remove:fs=p4 xs-up.btn-remove:txt-case=upper xs-up.btn-remove:w=(fit-content) xs-up.btn-remove:pos=rel xs-up.btn-remove:pointer-events=active! xs-up.btn-remove:icon-after=underline-left-to-right-scale xs-up.btn-remove:after:bw-bottom=(1px) xs-up.btn-remove:after:d=block xs-up.btn-remove:after:bottom=0 xs-up.btn-remove:hover:txt-underline=no xs-up.btn-remove:hover:icon-after=underline-left-to-right xs-up.cart-total-price:bw-top=(1px) xs-up.cart-total-price:flx-row-align=center-between xs-up.cart-total-price:fs=center-between xs-up.cart-total-price:ff=beta xs-up.cart-total-price:fs=h6 xs-up.cart-total-price:py=4 xs-up.btn-cta:fs=p4 xs-up.empty-cart:mt=4 xs-up.empty-cart:mb=auto xs-up.empty-cart:fs=h6 xs-up.empty-cart:ff=beta leo-cart-product-added-component-default default&quot;]/div[1]/div[@class=&quot;user-menu-wrapper state-mini state-user state-not-empty state-modal-open&quot;]/div[@class=&quot;user-menu-dropdown&quot;]/button[@class=&quot;btn-cta&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='undefined']/div/div/div/div[2]/button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AED 3,130.00'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue Shopping'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div[2]/button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'CHECKOUT' or . = 'CHECKOUT')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AED 2,385.00'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AED 870.00'])[5]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[2]/button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AED 650.00'])[5]/following::button[1]</value>
   </webElementXpaths>
</WebElementEntity>
