<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_id(TabbyPromo)</name>
   <tag></tag>
   <elementGuidId>210d7042-17d6-49a7-9dc3-661c0fede435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='katalon-rec_elementInfoDiv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#katalon-rec_elementInfoDiv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>katalon-rec_elementInfoDiv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>id(&quot;TabbyPromo&quot;)/div[@class=&quot;styles__tabby-snippet--750cf&quot;]/div[@class=&quot;styles__tabby-promo-snippet--6ce13&quot;]/div[@class=&quot;styles__tabby-promo-snippet__content--a65de&quot;]/span[@class=&quot;styles__tabby-promo-snippet__text--6fa34&quot;]/span[1]/b[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon-rec_elementInfoDiv&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='katalon-rec_elementInfoDiv']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='katalon']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COPYRIGHT © 2021 ALLSAINTS ALL RIGHTS RESERVED*ORDERS BEFORE 7PM'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/preceding::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='id(&quot;TabbyPromo&quot;)/div[@class=&quot;styles__tabby-snippet--750cf&quot;]/div[@class=&quot;styles__tabby-promo-snippet--6ce13&quot;]/div[@class=&quot;styles__tabby-promo-snippet__content--a65de&quot;]/span[@class=&quot;styles__tabby-promo-snippet__text--6fa34&quot;]/span[1]/b[1]']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'katalon-rec_elementInfoDiv' and (text() = 'id(&quot;TabbyPromo&quot;)/div[@class=&quot;styles__tabby-snippet--750cf&quot;]/div[@class=&quot;styles__tabby-promo-snippet--6ce13&quot;]/div[@class=&quot;styles__tabby-promo-snippet__content--a65de&quot;]/span[@class=&quot;styles__tabby-promo-snippet__text--6fa34&quot;]/span[1]/b[1]' or . = 'id(&quot;TabbyPromo&quot;)/div[@class=&quot;styles__tabby-snippet--750cf&quot;]/div[@class=&quot;styles__tabby-promo-snippet--6ce13&quot;]/div[@class=&quot;styles__tabby-promo-snippet__content--a65de&quot;]/span[@class=&quot;styles__tabby-promo-snippet__text--6fa34&quot;]/span[1]/b[1]')]</value>
   </webElementXpaths>
</WebElementEntity>
