<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_input_for_notification</name>
   <tag></tag>
   <elementGuidId>7673c043-af5e-407a-9fb3-23dd667e1df6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StockNotificationComponent&quot;)/div[@class=&quot;leo-stock-notification-component leo-stock-notification-component-product-back-in-stock-beta xs-up:px=3 xs-up.note:mb=2 xs-up.note:pr=7 xs-up.note:fc=beta xs-up.msg-success:p=4 xs-up.msg-success:txt-align=center xs-up[leo-validation-message]:pos=abs xs-up[leo-validation-message]:bottom=n1 xs-up.form-group:flx-row-align=stretch-left xs-up.form-group:scrollable=hidden xs-up.form-control:mb=0 xs-up.form-control:hmin=(50px)! xs-up.form-control:fs=p3 xs-up.form-control:focus:bs=none xs-up.btn-back-in-stock:btn=warning xs-up.btn-back-in-stock:bw=(1px) xs-up.btn-back-in-stock:bc=alpha xs-up.btn-back-in-stock:fc=black xs-up.btn-back-in-stock:mr=(-35%) xs-up.btn-back-in-stock:hmin=(50px)! xs-up.btn-back-in-stock:fs=p3 xs-up.btn-back-in-stock:br=0! sm-down.btn-back-in-stock:px=(0.75rem)! xs-up.btn-back-in-stock[disabled]:btn=warning xs-up.btn-back-in-stock[disabled]:bw=(1px) xs-up.btn-back-in-stock[disabled]:bc=alpha xs-up.btn-back-in-stock[disabled]:fc=black-50 xs-up.btn-back-in-stock[disabled]:fs=p3 xs-up.btn-back-in-stock:transition=(margin-right|0.35s|ease)! xs-up.form-control:focus~.btn-back-in-stock:mr=0 xs-up.form-control.ng-valid~.btn-back-in-stock:mr=0 product-back-in-stock-beta&quot;]/div[1]/div[@class=&quot;form-group invalid&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-invalid&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='email']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='StockNotificationComponent']/div/div/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Email Address']</value>
   </webElementXpaths>
</WebElementEntity>
