<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notify_when_product_back</name>
   <tag></tag>
   <elementGuidId>e1d14b14-1054-49fd-a7dc-1af5ffb188d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='StockNotificationComponent']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.note</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Type in your email address below to get notified when it is back in stock.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StockNotificationComponent&quot;)/div[@class=&quot;leo-stock-notification-component leo-stock-notification-component-product-back-in-stock-beta xs-up:px=3 xs-up.note:mb=2 xs-up.note:pr=7 xs-up.note:fc=beta xs-up.msg-success:p=4 xs-up.msg-success:txt-align=center xs-up[leo-validation-message]:pos=abs xs-up[leo-validation-message]:bottom=n1 xs-up.form-group:flx-row-align=stretch-left xs-up.form-group:scrollable=hidden xs-up.form-control:mb=0 xs-up.form-control:hmin=(50px)! xs-up.form-control:fs=p3 xs-up.form-control:focus:bs=none xs-up.btn-back-in-stock:btn=warning xs-up.btn-back-in-stock:bw=(1px) xs-up.btn-back-in-stock:bc=alpha xs-up.btn-back-in-stock:fc=black xs-up.btn-back-in-stock:mr=(-35%) xs-up.btn-back-in-stock:hmin=(50px)! xs-up.btn-back-in-stock:fs=p3 xs-up.btn-back-in-stock:br=0! sm-down.btn-back-in-stock:px=(0.75rem)! xs-up.btn-back-in-stock[disabled]:btn=warning xs-up.btn-back-in-stock[disabled]:bw=(1px) xs-up.btn-back-in-stock[disabled]:bc=alpha xs-up.btn-back-in-stock[disabled]:fc=black-50 xs-up.btn-back-in-stock[disabled]:fs=p3 xs-up.btn-back-in-stock:transition=(margin-right|0.35s|ease)! xs-up.form-control:focus~.btn-back-in-stock:mr=0 xs-up.form-control.ng-valid~.btn-back-in-stock:mr=0 product-back-in-stock-beta&quot;]/div[1]/div[@class=&quot;note&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='StockNotificationComponent']/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to favorites'])[1]/following::div[11]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notify Me'])[1]/preceding::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[1]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Type in your email address below to get notified when it is back in stock.']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[12]/div/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Type in your email address below to get notified when it is back in stock.' or . = 'Type in your email address below to get notified when it is back in stock.')]</value>
   </webElementXpaths>
</WebElementEntity>
